### ISSUE TITLE
Unable to initialize modular input "azure_monitor_metrics" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_monitor_metrics: script running failed (exited with code 1). 

### ISSUE THREAD

**Issue by cec0172** [Microsoft/AzureMonitorAddonForSplunk#100]
Noted another prior case with the same error.

Followed the same troubleshooting steps - reinstalled and received the same error message. 

Ran azure monitor_metrics.py and received the following. 

C:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin>python azure_monitor_metri
cs.py
Traceback (most recent call last):
  File "azure_monitor_metrics.py", line 32, in <module>
    from splunklib.modularinput import Script, Scheme, Argument
ImportError: No module named splunklib.modularinput  

I suspect a missing dependency, but cant figure out which one considering I have installed this app on another server without issue using the same steps.

**Comment by sebastus** [comment]
Newer release?

Missing = splunklib.

**Comment by cec0172** [comment]
Yes, this is an install of the newer version 1.3.1.

**Comment by cec0172** [comment]
That did it. 
Thanks!
