### ISSUE TITLE
Multiple subscriptions support

### ISSUE THREAD

**Issue by ricketyapps** [microsoft/AzureMonitorAddonForSplunk#101]
Trying to add more than one subscription but can't get it to work. With only one subscription, the feed to Splunk works fine. When setting up additional subscriptions I don't see the data from the new subscription to Splunk. No errors in logs. Anyone knows?

**Comment by sebastus** [comment]
There's a PR pending that fixes this. Sorry for the delay.

**Comment by ricketyapps** [comment]
Nice. Maybe a stupid question but I am not too familiar with how updates and releases work in this case. How would I know when it gets resolved? Thanks!

**Comment by sebastus** [comment]
check the status of the pull request.

**Comment by fredthebear** [comment]
Was this resolved? I'm using 1.3.2 and when I try to collect Azure Activity logs from multiple event hub namespaces I get "connot read property 'write' of null. Sorry if I need to open a separate issue for this... 

`03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Timer.listOnTimeout (timers.js:207:5)
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at tryOnTimeout (timers.js:237:5)
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at ontimeout (timers.js:365:14)
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Timeout._onTimeout (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/link.js:270:12)
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at ReceiverLink.Link.attach (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/link.js:152:27)
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Connection.sendFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:329:10)
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Object.frames.writeFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/frames.js:64:9)
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" TypeError: Cannot read property 'write' of null
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"         ^
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"   stream.write(buffer, callback);
03-04-2019 16:39:18.888 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" /opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/frames.js:64
`

**Comment by sebastus** [comment]
It's PR#89. Still open. 

At this time, you can only have one of each data input per instance of the TA.

**Comment by brettwilliams101** [comment]
I'm also needing the functionality added in #89.  If I need to run multiple, can I run multiple copies of the TA on the same heavy forwarder as long as the directory names are unique?

**Comment by sebastus** [comment]
That work hasn't been completed yet.

**Comment by GarethR-UK** [comment]
Is there any workaround for this. Is using the same app id / secret for multiple event hubs in multiple subscriptions a valid workaround. My Splunk infrastructure is not in Azure.

**Comment by sebastus** [comment]
The best solution is to use the Azure Function/HEC implementation. 

https://github.com/microsoft/AzureFunctionforSplunkVS 

You might be able to install multiple copies of the add-on, but each one can only work with a single hub namespace. I haven't tried it.
