### ISSUE TITLE
Configurable tag key and option to "ignore tag value"

### ISSUE THREAD

**Issue by sebastiankasprzak** [microsoft/AzureMonitorAddonForSplunk#105]
We have a requirement to provide ability to perform collection of Azure Monitor metrics for resources with specific already existing tag.

Currently the app requires that "Metrics" tag key is used on all of the resources.

https://github.com/Microsoft/AzureMonitorAddonForSplunk/blob/b7bc5cba00ecaebd5b0bc935885bc1aa544ef0c6/bin/subs.py#L229

I would like to propose following change:

`inputs.conf` stanza example:
```
[azure_monitor_metrics://<name>]
SubscriptionId = xxxxxx
index = azure_metrics
interval = 60
sourcetype = amm:metrics
MetricsTagKey = CustomTag
IgnoreTagValue = true
```

and convert `get_requested_metrics` function to look more less like this:

```
    # if no metrics tag, skip it
    metrics_tag = tags.get(metrics_tag_key, None)
    if metrics_tag is None:
        return None

    if len(metrics_tag) == 0:
        return None

    set_of_requested_metrics = set()
    if metrics_tag == '*' OR ignore_tag_value == True:
        metrics_tag = ALL_AVAILABLE_METRICS
    set_of_entered_metrics = set(metrics_tag.split(','))
    for metric in set_of_entered_metrics:
        set_of_requested_metrics.add(metric.strip())
```

Would you be happy to accept a contribution that implements this change @sebastus ? I'm happy to carry out the work and submit a PR.

**Comment by sebastus** [comment]
If I understand you correctly, you want to collect all available metrics if:
1. there is a Metrics = * tag  OR
2. there is any tag at all on the resource and a switch called "ignore_tag_value"

Is that right? If so, it looks fine to me. I've thought of adding such a thing in the past.
