### ISSUE TITLE
Can this app pull Identity risk events.

### ISSUE THREAD

**Issue by mpras123** [microsoft/AzureMonitorAddonForSplunk#112]
First of all, the app works as expected.  Wondering if this app can also pull Azure Identity risk events.
ref: https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-reporting-api the data that is exposed through the identity risk events has lot of interesting information.

**Comment by sebastus** [comment]
this page details the AAD telemetry that is shipped out through Activity
Logs in Azure Monitor:

https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-activity-logs-azure-monitor

To find out for sure what's included and what's not, generate the event
with a test and confirm it in the Azure Monitor portal app. Then check to
see if it arrives in Splunk via the Activity Log.

I don't happen to know the detailed answer to your question.
