### ISSUE TITLE
at Timer.listOnTimeout (timers.js:214:5) - not able to pull Sing-in Logs

### ISSUE THREAD

**Issue by mpras123** [microsoft/AzureMonitorAddonForSplunk#113]
Everything was working fine until yesterday, but now the app is only managed to pull AuditLogs, not sign-logs.
ERROR ExecProcessor - message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"     at Timer.listOnTimeout (timers.js:214:5)
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" at Timer.listOnTimeout (timers.js:214:5)
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" at tryOnTimeout (timers.js:250:5)
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" at ontimeout (timers.js:386:11)
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" at Timeout._onTimeout (/apps/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/link.js:270:12)
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" at ReceiverLink.Link.attach (/apps/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/link.js:152:27)
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" at Connection.sendFrame (/apps/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:329:10)
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" at Object.frames.writeFrame (/apps/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/frames.js:64:9)
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" TypeError: Cannot read property 'write' of null
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" ^
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" stream.write(buffer, callback);
message from "/apps/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" /apps/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/frames.js:64

**Comment by sebastus** [comment]
This error originates in a module that I have no control over. Is it
occurring each time the TA runs? In the past, it was more intermittent and
would only occur infrequently. If it occurs every time the TA runs, then it
prevents messages from being indexed.

**Comment by mpras123** [comment]
i guess it is occurring for each poll interval(60 seconds).  it all started just 2 days ago, the good thing it is still pulling down auitlogs, shouldn't this happens for both(audit & Sign-in).  Is there a workaround to resolve this issue.

**Comment by sebastus** [comment]
the TA reads hubs in parallel, but both audit logs and sign-in logs come
through Activity Log. There must be something special about the sign-in
logs, or the number of messages, etc, that are causing the error to occur.
This is the closest thing to a pattern I've seen in 2 years. You could try
switching off the sign-in logs export to hub to see if the error goes away
just to confirm.

The path beyond is murky. Like I said, that module (amqp10) is not mine. I
have raised this issue but never gotten any love for it. The other
alternative is to rewrite the logs data input in python, which could be
done now due to a new library from Microsoft. The question there is the
time.

Do you have a Python developer handy that can contribute?

**Comment by sebastus** [comment]
I discovered that if the TA tries to access a hub that does not exist, the stream.write error occurs 100% of the time. This is a new condition - it only did it intermittently in times passed. Delete all hubs from hubs.json that do not exist in the hub namespace. This should fix the problem.
