### ISSUE TITLE
Error AADSTS700016 and authentication error

### ISSUE THREAD

**Issue by robertoveg4** [microsoft/AzureMonitorAddonForSplunk#114]
Hi,

After installing this add on (by following the documentation here: https://www.splunk.com/blog/2018/04/20/splunking-microsoft-azure-monitor-data-part-1-azure-setup.html), everything was working fine for a few weeks. Since December 22nd, the add on stopped working. In Splunk logs, I have the following error:

{"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '********' was not found in the directory '[REDACTED]'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant\r\nTrace ID: 74e5f6ee-[...]-f2451ea63700\r\nCorrelation ID: da344709-[...]-5e1ae46072b4\r\nTimestamp: 2018-12-22 14:57:33Z","error_codes":[700016],"timestamp":"2018-12-22 14:57:33Z","trace_id":"74e5f6ee-[...]-f2451ea63700","correlation_id":"da344709-[...]-5e1ae46072b4"}

The error AADSTS700016 is not listed on the error webpage https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes

The only workaround I found was to delete the add on in Splunk and reset the parameters (SPNTenantID, SPNApplicationID, etc...).

The add on is deployed on two Splunk instances, each linked to a different tenant and the same problem occurs: after a while, the logs are not retrieved and I get the error above and I have to reset the parameters of the add on.

Any idea of what could be the cause of this error? 
Thanks for your help.

**Comment by sebastus** [comment]
It looks like you updated the add-on? Any time the add-on is re-installed, the creds must be re-instantiated. The hint is that it's looking for an app with identifier '*****'. This is the obfuscated app id that's normally replaced by the actual app id. Deleting or updating the app causes the storage password to be deleted.

**Comment by sebastus** [comment]
Actually, anytime you go to the creds page for a data input and save, you have to re-enter the app id and app key. or the asterisks will be saved over the actual password that's stored in storage passwords.
