### ISSUE TITLE
AmqpProtocolError: com.microsoft:argument-error:The supplied offset '6#######' is invalid.

### ISSUE THREAD

**Issue by rmmalon** [Microsoft/AzureMonitorAddonForSplunk#116]
Had the add-on working for awhile, then deleted and recreated the event hub.  Now getting amqp offset is invalid error.  Restarts of splunk and splunk host did not help.  Recreating data input did not help.  Upgrading Add-on to latest version did not help.

**Comment by sebastus** [comment]
Looks like you might need to delete the checkpoint file. If you switch on
DEBUG logging for ExecProcessor, you'll see some logs referencing the
actual file location.

**Comment by rmmalon** [comment]
Yes that worked - enabled debug for ExecProcessor, found checkpoint file location in splunk by searching: index="_internal" "ta-azure_monitor" "checkpoint", renamed the checkpoint .json file, watched a new checkpoint file get created and logs are flowing again.  Thanks.
