### ISSUE TITLE
TypeError: Cannot read property 'write' of null  (frames.js:64:9)

### ISSUE THREAD

**Issue by 1trevor** [Microsoft/AzureMonitorAddonForSplunk#118]
I'm receiving this error in the splunkd log every minute. No data is being ingested. I have double-checked the configuration in Azure and Splunk multiple times. Any idea what could be causing this?
```
ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"
TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/frames.js:64:9)
    at Connection.sendFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:329:10)
    at Connection.sendFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:329:10)
    at Timeout._onTimeout (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/link.js:270:12)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by sebastus** [comment]
Remove from hubs.json any hub that does not exist in the namespace.

**Comment by 1trevor** [comment]
This is what I see in hubs.json. Are these all supposed to be event hub names? Where did this list come from? I don't have any of these event hubs.
```
{
    "insights-logs-workflowruntime": "workflowId",
    "insights-logs-networksecuritygrouprulecounter": "resourceId",
    "insights-logs-networksecuritygroupevent": "resourceId",
    "insights-logs-applicationgatewayaccesslog": "resourceId",
    "insights-logs-applicationgatewayperformancelog": "resourceId",
    "insights-logs-applicationgatewayfirewalllog": "resourceId",
    "insights-logs-loadbalanceralertevent": "resourceId",
    "insights-logs-loadbalancerprobehealthstatus": "resourceId",
    "insights-logs-auditevent": "resourceId",
    "insights-logs-servicelog": "resourceId",
    "insights-logs-integrationaccounttrackingevents": "resourceId",
    "insights-logs-joblogs": "resourceId",
    "insights-logs-jobstreams": "resourceId",
    "insights-logs-audit": "resourceId",
    "insights-logs-signin": "resourceId",
    "insights-logs-signinlogs": "resourceId",
    "insights-logs-requests": "resourceId",
    "insights-logs-requestlogs": "resourceId",
    "insights-logs-operationallogs": "resourceId",
    "insights-logs-execution": "resourceId",
    "insights-logs-authoring": "resourceId",
    "insights-logs-alerts": "resourceId"
}
```

**Comment by sebastus** [comment]
They are a default set. I learned recently that only existing hubs should
be in the file. Do you know how to get that list?

**Comment by 1trevor** [comment]
So I changed it to this but I still get the same error. Do I have the format correct? The value should always be "resourceId"? I noticed the first one in the default list is "workflowId"
```
{
    "insights-logs-auditlogs": "resourceId",
    "insights-logs-signinlogs": "resourceId"
}
```

**Comment by sebastus** [comment]
It looks fine. Do both hubs have 4 partitions?

**Comment by 1trevor** [comment]
Yes they do.

I also see in the debug logs that it's trying to access a hub called insights-operational-logs, which is hardcoded in bin/app/azure_monitor_logs.js:514

Should I create a hub with that name?

**Comment by sebastus** [comment]
That sounds like activity log. Did you set them to export?

**Comment by 1trevor** [comment]
I set the Azure Active Directory Activity logs to export, which created 2 event hubs - insights-logs-auditlogs and insights-logs-signinlogs. Those are the only things I'm trying to ingest at the moment.

**Comment by sebastus** [comment]
How many data inputs did you configure?

**Comment by 1trevor** [comment]
Just the one for Activity log. I just configured the same settings under diagnostic logs and it's working now. The issue is resolved.

Is there any documentation that explains the difference between the Activity/Diagnostic/Metrics inputs and when to use each one?

**Comment by sebastus** [comment]
I'm pretty sure the wiki explains it. I'll answer more fully tomorrow. I'm
in Britain. Bedtime. 😴
