### ISSUE TITLE
What does this error message point at ? Error getting event hub creds ?

### ISSUE THREAD

**Issue by droodleskins** [microsoft/AzureMonitorAddonForSplunk#121]
```
2/11/1911:42:26.836 PM | 02-11-2019 12:42:26.836 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" Modular input azure_diagnostic_logs://account_diagnostics Error getting event hub creds: StatusCodeError: 403 - {"error":{"code":"Forbidden","message":"Access denied","innererror":{"code":"AccessDenied"}}}host =	azsal0317source =	/opt/splunk/var/log/splunk/splunkd.logsourcetype =	splunkd
-- | --
  | 2/11/1911:41:58.893 PM | 02-11-2019 12:41:58.893 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://account_activity Error getting event hub creds: StatusCodeError: 403 - {"error":{"code":"Forbidden","message":"Access denied","innererror":{"code":"AccessDenied"}}}
```

**Comment by sebastus** [comment]
Probably means that your service principal can't read the secret from the key vault.

**Comment by droodleskins** [comment]
To check our configuration, I’ve verified the that the Service Principal is able to access the keyvault by running the following Azure CLI command lines:

az login --service-principal -u 301c3a03-487b-4989-a28e-xxxxxxxxx -p <removed for security> --tenant <removed for security>
Success!

az keyvault secret show --vault-name keyvaultstest-certs --name aglsapsyncnonprodeventhub
Success!

The first line logs in using the service principal.  The second line returns the key I requested.  I can list the secrets as well as show one.

Also, I’ve checked the secret (RootManageSharedAccessKey) in the keyvault matches the RootManageSharedAccessKey in event hub.

I hope this helps with debugging.  Please reach out if you have any questions.

**Comment by sebastus** [comment]
This was working for you back in November. What changed?

**Comment by droodleskins** [comment]
different service principle configured by someone else .. never got that one working in Nov

**Comment by sebastus** [comment]
what's the difference between the two spn's? why do we need another one?

**Comment by droodleskins** [comment]
sorry i mean different event hub for a different subscription

**Comment by sebastus** [comment]
are you able to do a screen share? would be quicker.
