### ISSUE TITLE
Azure Monitor - Logging

### ISSUE THREAD

**Issue by petegriggs** [Microsoft/AzureMonitorAddonForSplunk#124]
Hello.

The addon is in Splunk and the input type is configured however don't appear to be getting any Azure data in. Is there away of testing and confirming connection. I can't see any logging for the app? Can someone point me in the right direction please?

Thanks
Peter.

**Comment by sebastus** [comment]
which data input?

**Comment by petegriggs** [comment]
All data input - I am currently unable to see anything. Do you have a connection test or similar? The add-on was install by a colleague so not sure what he did. I have confirmed the config with Azure and all looks correct just doesn't seem to be pulling data in.

**Comment by sebastus** [comment]
switch to debug level logging for ExecProcessor in Splunk server settings.
in Azure, create a resource group and watch for that event to show up in
the Azure Monitor blade of the portal.
watch the splunkd.log file: the way I do it is  "tail -f splunkd.log | grep
azure", but maybe you want to use splunk to do that query.
you should see the add-on authenticating, connecting to the event hub
partitions, and getting messages.

**Comment by petegriggs** [comment]
I don't appear to see anything on it. It's installed on a windows heavy forwarder - Will poke around the logs.

**Comment by petegriggs** [comment]
When I load the app in Splunk just getting a white screen with a hyperlink to Splunk - Appears to be some inputs but can't see anywhere to setup the logging. Or do I need to set Splunk to debug logging?

**Comment by sebastus** [comment]
You go to "manage apps" and then usually load the app from a file, where
you have pulled the file from Releases in the github repo. Then you
configure the data inputs in Settings / Data Inputs.

To see the details of the add-on operation, you set ExecProcessor to Debug
level logging within Settings / Server Settings.
