### ISSUE TITLE
Is the Service Bus  Connectivity Mode set to Auto Detect, Http, or Tcp?

### ISSUE THREAD

**Issue by Stockwel** [Microsoft/AzureMonitorAddonForSplunk#127]
Hi,
Is the Service Bus  Connectivity Mode set to Auto Detect, Http, or Tcp? Collecting Firewall Port Requirements for the Splunk HF.

Thanks!

**Comment by sebastus** [comment]
Opening the connection to the event hub namespace is handled by an underlying library. It is here: https://github.com/noodlefrenzy/node-amqp10. The connection string resembles: amqps://xxx.servicebus.windows.net. Port 443 is required on the Splunk box.

**Comment by Stockwel** [comment]
Thank you for the prompt response!  Any chance you will be using this
library in the future?  https://github.com/amqp/rhea.  I am looking to test
your add-on with port 5672\5671, instead of 443 and see if there is a
noticeable speed difference?

Thank You!

**Comment by sebastus** [comment]
I doubt it. If I refactor the logs data input, I'll very likely use the
Microsoft python libraries instead of node.js again.
