### ISSUE TITLE
Consumer Group

### ISSUE THREAD

**Issue by ahfinch** [microsoft/AzureMonitorAddonForSplunk#128]
I want to possibly pull eventhub data down to different environments from the same azure eventhub source.  As I understand, consumer groups allow me to do this.  

How to I integrate consumer group configuration into this module?

**Comment by ahfinch** [comment]
Looks like I found my answer.  In bin/app/azure_monitor_logs.js it is hardcoded:

630                 var recvAddr = hub + '/ConsumerGroups/$default/Partitions/';

$default represents the consumer group.  $default is the one that microsoft generates upon eventhub creation, but the user can add more (up to 20).

Is there a chance you can make this a variable and an option for this module.  Having multiple consumer groups on the same eventhub allows me to query the data from two independent environments within the Azure eventhub.

**Comment by sebastus** [comment]
Adding consumer group as a variable is a reasonable ask. I'll add it to the list. Perhaps someone in the community can add it and submit a PR?
