### ISSUE TITLE
Limitations? Any use cases where this is used at scale ?

### ISSUE THREAD

**Issue by LarsFromMars** [microsoft/AzureMonitorAddonForSplunk#129]
Are there any documented use cases where this is used at scale ?
Talking a multi subscription site (30+) of over 1000 Azure VM's which can be in different locations.
Looking at a base level of monitoring initially cpu, disk, memory - and build from there.
With the collection node being a single (Azure apps Only) Splunk Heavy forwarder.
?

**Comment by sebastus** [comment]
I'm aware of companies with >70 subscriptions using it. But I don't install it myself in these places so I can't provide any details.

**Comment by bdschaap** [comment]
Have you progressed in the use of this add-on in your environment?  I'm curious what your experience has been using it at scale.

Long term I'll have an Azure footprint that may be similar to yours.  We'll have a combination of IaaS infrastructure from a Lift & Shift effort.  We'll also have PaaS based resources as we modernize our platform.

**Comment by sebastus** [comment]
I don't personally have a very large environment. Other users that have
implemented the TA for dozens of subscriptions.

I have yet to hear from anyone saying it can't keep up.

**Comment by gdv-deepakk** [comment]
@bdschaap 
Can you share your experience so far. I am in process of setting this for our Azure Environment which will eventually will have 8+ Subscriptions in 3+ Regions and as you explained in 1st comment my plan is to have 1 HvyFwdr with this App per region to collect just Diag/Activity logs of all resources across all Subscriptions per region. I will share my experience one I hit the scale. For now can you share your experience so far.

**Comment by bdschaap** [comment]
We'll have production workloads running in Azure in 2019 H2.  There won't be significant activity though.  It will be farther down the road before we'll have a significant amount of activity.

**Comment by bdschaap** [comment]
Side note on experiences... my biggest issue to date is https://github.com/microsoft/AzureMonitorAddonForSplunk/issues/141.  I'd be interested in whether you are experiencing the same thing if you're using that approach for ingesting metrics.

**Comment by gdv-deepakk** [comment]
@bdshaap
We have no plans to collect metrics and ingest to Splunk. We are only thinking of ingesting diag and activity for SEIM Analysis.

**Comment by bdschaap** [comment]
For diagnostic logs, I wasn't able to find any logs at the transaction level for either Service Bus or Event Hubs.  This is unrelated to this TA but wanted to mention it in case you are using either of those PaaS resources.  See https://github.com/MicrosoftDocs/azure-docs/issues/27653 and https://github.com/MicrosoftDocs/azure-docs/issues/30673 for more information.  I would suggest reviewing the contents of the diagnostic logs you plan to ingest to ensure it's the level of detail you expect.

**Comment by gdv-deepakk** [comment]
@bdschaap
For resource level diag logs we are depending on Azure Log Analytics. We are only send SIEM type diag logs to Splunk as defined in this App. Still working on configuration as we have enterprise level policies and restrictions to get certain access it's getting delayed. Can't wait to share my experience of using this App for our use case
