### ISSUE TITLE
Can we send to a different Index?

### ISSUE THREAD

**Issue by Stockwel** [microsoft/AzureMonitorAddonForSplunk#130]
Hi,
I tried changing the index from main to a different index via the inputs.conf within the Addon but the Addon still continues to send to main index. Is it possible to send to an alternate index other than the offerings in the GUI?

Thanks!

**Comment by sebastus** [comment]
Great question, and honestly no one has ever asked. I assumed that people
would input the index they want on the page where the data input is
configured under "More Settings". Is this what would end up in inputs.conf?
Anyway, you can force it by making a tiny alteration in the code.

If you're curious about the model I used to write the code, it's on this
page under "The stream_events method" section.
http://dev.splunk.com/view/python-sdk/SP-CAAAER3

The workaround is this:

Find these 5 lines in azure_monitor_logs.js in the bin/app directory of the
TA: (should be at about #408)

var curEvent = new Event({
stanza: name,
sourcetype: sourceType,
data: data
});

Insert a line like this:
   index: <your index name>,

so it'll look like this:

var curEvent = new Event({
stanza: name,
index: myIndex,
sourcetype: sourceType,
data: data
});


That should do it.

Let us all know how it goes.

Thanks,
Greg

**Comment by Stockwel** [comment]
Hi,
Thank you so much for this info. Appreciate it!   I did make the changes
you suggested but the events still continued to go to "main".  I will poke
around some more and see if I come up with something.

Best Regards, Andie

**Comment by gdv-deepakk** [comment]
@Stockwel 
Why not make change directly in `inputs.conf` as following and restart Splunk
```bash
[azure_activity_log://sp-splunk-activitylog]
SPNApplicationId = ********
SPNApplicationKey = ********
SPNTenantID = ********
eventHubNamespace = EH-PROD
index = azure-act
interval = 60
secretName = eh-creds
secretVersion = ********
sourcetype = amal:activityLog
vaultName = kv-splunk-prod
disabled = 0

[azure_diagnostic_logs://sp-splunk-diaglog]
SPNApplicationId = ********
SPNApplicationKey = ********
SPNTenantID = ********
eventHubNamespace = EH-PROD
index = azure-diag
interval = 60
secretName = eh-creds
secretVersion = ********
sourcetype = amdl:diagnosticLogs
vaultName = kv-splunk-prod
```

I haven't tried per event type yet, but have plans to try that using props and transforms when I reach to that stage of implementation.

@sebastus 
_I assumed that people would input the index they want on the page where the data input is configured under "More Settings". Is this what would end up in inputs.conf?_
Your assumption is right changes in UI will reflect in `inputs.conf`.
