### ISSUE TITLE
Azure eventhub checkpointing?

### ISSUE THREAD

**Issue by ahfinch** [microsoft/AzureMonitorAddonForSplunk#131]
Does the eventhub client code perform any check-pointing back to the Azure eventhub?  

I want to Y-split the eventhub data and implement separate PROD and TEST servers to obtain the full data set for both environments.  Consumer groups would provide the typical way this is achieved.  My research shows that this module hard codes the consumer group currently, so at this point in time there you can only connect via the $default consumer group.

I was wondering if this would still work as long as this module does not checkpoint back to the Azure eventhub server.   If check-pointing is handled entirely client side (or via Splunk Module), then this might work with a single consumer group across two different consuming servers.

Anyone have experience with how this is handled for this Splunk module?

This issue is related to my post listed here regarding consumer groups:

https://github.com/Microsoft/AzureMonitorAddonForSplunk/issues/128

**Comment by sebastus** [comment]
The module that interacts directly with the event hub is amqp10, available
on npm. My code acquires checkpoint information from that module and writes
it to a checkpoint file in Splunk's file system. If you want to examine the
checkpoint data, locate the file by switching on debug logging for
ExecProcessor for a couple of minutes. The location of the checkpoint file
is logged in splunkd.log.

Why not install the TA on each of the servers, leave $default consumer
group coded on Prod and modify the consumer group to something else on Test?

**Comment by ahfinch** [comment]
I did look through the code and it seemed to me that checkpointing was done locally, but I am not as familiar with this module as you are :)  Thanks for the help there.

I decided to run a test right now with two different Splunk instances running this module and both configured to go back to the same eventhub in Azure.  My initial spinup of the 2nd Splunk server ingested 1 day of backlog, so I think Eventhub will offer any backlog data that it has if it has never been "checkpointed" on the server.  I am letting my test run for about a week to see if both instances import the same data.

I am reluctant to make a change for the consumer group within the code because of the Splunk Auto-Update feature that my client uses to keep all of his software Splunk modules updated.  Any update to that source file will clobber my edits.  Hence, I think a better approach is to pull this data from the splunk app.conf file or another Splunk App config file.  These files are likely to be unaltered during a minor revision update and would survive the update process unaltered.

**Comment by sebastus** [comment]
This TA is not Splunk managed or certified for various reasons. Auto-update
isn't going to touch it.

Each new consumer group gets its own set of checkpoints. So if you create a
new consumer group and start ingesting from it, you're going to get
everything going back to the limits of your retention period.

**Comment by brettwilliams101** [comment]
Check out https://docs.splunk.com/Documentation/Splunk/latest/AdvancedDev/ModInputsCheckpoint.

**Comment by sebastus** [comment]
very helpful. thanks!

**Comment by gdv-deepakk** [comment]
@ahfinch 
Is this still considered as open issue? if not can the maintainers close this issue so its less confusing.
