### ISSUE TITLE
Error getting event hub creds: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by brettwilliams101** [microsoft/AzureMonitorAddonForSplunk#132]
I am successfully pulling data from our event hub, but I must run the forwarder as root in order to do so.  If I run this under our service account, I get this error:

```
Error getting event hub creds: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
```

**Comment by sebastus** [comment]
A couple of searches yielded the suggestion that a proxy server or similar was getting in the way. Could that be possible for your service account?

**Comment by brettwilliams101** [comment]
I wouldn't think so.  I have direct outbound FQDN firewall openings for my on-prem servers.  It seems that node is trying to bind to loopback.  Also, the apps were setup as root, but I changed permissions to our service account and added execute permissions recursively.  Maybe I can kick off the script interactively from the shell and view output that way?

**Comment by brettwilliams101** [comment]
If something tries to bind to port 80, even on loopback, I don't think Linux allows it unless it's root.  So, whatever is talking on port 80, I need to find it and set that to a higher (greater than 1024) port.  I think that should solve the issue.

**Comment by brettwilliams101** [comment]
so I tried unsetting my HTTP proxy environmental variables in the script which launches the rest of the app.  This seems to have worked.  I traced the error to originating from the _tunnel_ module, which is referenced by _ms-rest/lib/filters/proxyFilter.js_.  Hopefully this makes sense and it's actually fixed.

**Comment by sebastus** [comment]
Thanks for sharing that with the community, Brett. Cheers!
