### ISSUE TITLE
should we get memory metrics from eventhubs

### ISSUE THREAD

**Issue by LarsFromMars** [microsoft/AzureMonitorAddonForSplunk#135]
we have turned on memory metrics in Azure portal but not seeing anything - we only have ..

Disk Read Bytes | 240 | 14.286% |  
Disk Read Operations/Sec | 240 | 14.286% |  
Disk Write Bytes | 240 | 14.286% |  
Disk Write Operations/Sec | 240 | 14.286% |  
Network In | 240 | 14.286% |  
Network Out | 240 | 14.286% |  
Percentage CPU

**Comment by sebastus** [comment]
What do you mean by "turned on memory metrics"?
Are you using the metrics data input?
What resources did you tag?
Did you attempt to send metrics through an event hub? (this won't work
correctly)

**Comment by LarsFromMars** [comment]
I mean we have attempted to send memory metrics to the eventhub using the metrics data input

sourcetype is amm_....

what do you mean this wont work correctly ?

thanks

**Comment by sebastus** [comment]
The metrics data input queries the ARM api for metrics from the resources
that you have tagged. Creating a diagnostics profile and sending metrics to
an event hub is redundant. The message stream that goes to the event hub
for metrics won't be correctly structured and will be ignored by the
add-on. There should not be a metrics event hub listed in hubs.json.

**Comment by LarsFromMars** [comment]
OK so this is my bad - have just checked my config and we have the REST API configured which is giving us the above metrics..

So whats missing to get the memory metrics please ?

**Comment by sebastus** [comment]
On each resource that you want to monitor, add a tag such as "Metrics" as
the key and "*" as the value. This will work for most resource types. If
you have any redis caches, don't use "*". There are too many metrics -
you'll have to pick out the ones you want. The wiki in the github repo has
further details.

**Comment by LarsFromMars** [comment]
OK will re-check but pretty sure we've followed the wiki and did that.

**Comment by LarsFromMars** [comment]
Confirmed this is done by the Azure admin tag=metrics * as value - how do we troubleshoot further?

we are getting metrics for CPU, network, disk - still no memory?

**Comment by LarsFromMars** [comment]
Reading the Azure documentation - i cannot see that we can get memory metrics for vm instances ? can you confirm ?

**Comment by sebastus** [comment]
That's correct. You get instance level metrics and logs from the Splunk
Universal Forwarder or another agent like the OMS agent (now MMA) or the
WAD agent.

**Comment by LarsFromMars** [comment]
whats the point in using the event hub at all then?

**Comment by sebastus** [comment]
Logs
