### ISSUE TITLE
Configured Inputs for Activity & Diagnostic Logs but no data being indexed in Splunk.

### ISSUE THREAD

**Issue by atgithub11** [microsoft/AzureMonitorAddonForSplunk#138]
Hi,

We went through all the configurations and are finally in a place where the Add-on is functional without any errors. PCAP shows that Splunk has an active connection and Azure is sending Application Data to it. On Azure site as well, we can see that logs are getting generated and are also consumed when requested by Splunk. 

But despite all this, there is not a single event being indexed on Splunk side. For both Inputs(Activity & Diagnostic) I created a new Index called "azure" to easily identify the data. Sourcetypes are kept with default values, i.e. amal:activityLog and  amdl:diagnosticLogs respectively.

Following can be seen in logs once we enable DEBUG logging for execprocessor.

04-17-2019 15:18:19.157 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure_Activity_Log Checkpoint file name is: /opt/splunk/var/lib/splunk/modinputs/azure_activity_log/Azure_Activity_Log_checkpoints.json
04-17-2019 15:18:19.158 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure_Activity_Log Checkpoint file name is: /opt/splunk/var/lib/splunk/modinputs/azure_activity_log/Azure_Activity_Log_checkpoints.json
04-17-2019 15:18:19.168 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure_Activity_Log Time is now: 2019-04-17T19:18:19.168Z
04-17-2019 15:18:19.325 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure_Activity_Log createPartitionReceiver for hub: insights-operational-logs and partition: 0
04-17-2019 15:18:19.327 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure_Activity_Log createPartitionReceiver for hub: insights-operational-logs and partition: 1
04-17-2019 15:18:19.328 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure_Activity_Log createPartitionReceiver for hub: insights-operational-logs and partition: 2
04-17-2019 15:18:19.328 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure_Activity_Log createPartitionReceiver for hub: insights-operational-logs and partition: 3 

What else can I do to find where the data is going? 

Thanks,

~ Abhi

**Comment by sebastus** [comment]
the log tells me that the add-on is successfully accessing the event hub
for activity logs. take a look at the traffic in that event hub through the
azure portal. ensure that you see messages going in and, hopefully, out. If
you see them going out, you should see them in Splunk. Unless there is
another client for the hub that is grabbing the messages before splunk can
get them. *hint*
