### ISSUE TITLE
Setting up TA for audit logs

### ISSUE THREAD

**Issue by karenmcauley** [Microsoft/AzureMonitorAddonForSplunk#139]
Hi,

We are getting the activity logs in and have added the audit logs to the same eventhub, however we aren't getting these into splunk.  Is there additional or different set up required to get the audit logs into splunk?  We can see that audit logs are listed in logCategories.json.  Your help is much appreciated.

Thanks

Karen

**Comment by sebastus** [comment]
What is the hub name? Did you put it into hubs. Json?

**Comment by karenmcauley** [comment]
Hi,

hubs.json contains the following:

{
    "insights-logs-auditlogs": "resourceId"
}

Is that correct?

**Comment by sebastus** [comment]
Does it exist?

**Comment by karenmcauley** [comment]
insights-logs-auditlog matches the name of the eventhub which was created for audit logs in the eventhub namespace.

**Comment by sebastus** [comment]
Is the diagnostic logs data input configured?

**Comment by karenmcauley** [comment]
Not in this event hub namespace. It was successfully tested in a different namespace and then disabled.

**Comment by sebastus** [comment]
The only hub served by activity log data input is
insights-operational-logs. The rest are served by diagnostic logs data
input.

**Comment by karenmcauley** [comment]
I will try that. Thanks for your help.

**Comment by karenmcauley** [comment]
That worked perfectly! Thank-you.

**Comment by pterrynss** [comment]
Can I see an example of what the hubs.json file should look like? I initially created an Azure Event Hub, and even though I specified that hub in the setup script for the AzureMonitorAddOn, it created a different Event Hub with splunk in the name (not sure if this is intentional), so now I'm wondering what I put in the hubs.json file.

Example:
`
{
  "myEventHub": "resourceid"
  "splrandom": "resourceid"
}
`

Or do you actually put the resource ids?
`
{
  "myEventHub": "/subscriptions/4erestofthesubid"
  "splrandom": "/subscriptions/4drestofthesubid"
}
`

**Comment by karenmcauley** [comment]
Hi,

An example of hubs.json that works for us is:

{
    "insights-logs-alert": "resourceId",
    "insights-logs-auditlogs": "resourceId",
    "insights-logs-signinlogs": "resourceId"
}

"resourceId" is exactly that literal string, not a value unique to your set up.  Your hubs.json could look exactly like the one I pasted above depending on what you are trying to onboard.

**Comment by pterrynss** [comment]
Did you create eventhubs in Azure with those exact names?

**Comment by karenmcauley** [comment]
Hi,

You can call the eventhub whatever name you like, those are like container names which azure creates automatically when you start logging.  When you go to diagnostics settings and click that you are sending audit logs and signinlogs to the eventhub, these will be created with the names specified above - insights-logs-auditlogs and insights-logs-signinlogs.  Like in this screenshot below, except you will click "Stream to an event hub".  We are sending all 3 to a single eventhub.

![Screen Shot 2019-07-01 at 09 10 06](https://user-images.githubusercontent.com/18612708/60420623-12afc700-9be0-11e9-917a-f430de1087c5.png)

**Comment by pterrynss** [comment]
Ah, I see. Is there a spot where you can actually see the container names, so I can verify mine are named the same? I don't see the container names in your screenshot. Thanks so much for your responsiveness!

**Comment by karenmcauley** [comment]
Hi,

I've edited my comment above to use more correct terminology.  If you look at the eventhub **namespace** (you can choose your own name for this), where it shows you the charts, you will see the eventhubs at the very bottom of that page - these are named by azure.  This screenshot below says "no event hubs yet" where the event hub names (insights-logs-alert, insights-logs-auditlogs and insights-logs-signinlogs) would be:

![Screen Shot 2019-07-02 at 08 57 05](https://user-images.githubusercontent.com/18612708/60494801-6fc28000-9ca7-11e9-8bbf-d07f9c3c8af5.png)

The following blog posts by the author of the TA might also be useful:

https://www.splunk.com/blog/2018/04/20/splunking-microsoft-azure-monitor-data-part-1-azure-setup.html
https://www.splunk.com/blog/2018/05/07/splunking-microsoft-azure-monitor-data-part-2-splunk-setup.html

Also, you can find additional categories in the logCategories.json file in the TA.  We are also bringing in alerts from Security Graph (which is line 26 in that file - this must be added to the hubs.json if you intend to use it) - we get MCAS, IPC and ASC alerts into an eventhub using the Security Graph.  Instructions on that are here:
https://docs.microsoft.com/en-us/graph/security-splunk-siemintegration

Hope this helps,

Karen

**Comment by sebastus** [comment]
Karen - really appreciate the assist.
