### ISSUE TITLE
Are Metric Dimensions Supported?

### ISSUE THREAD

**Issue by bdschaap** [microsoft/AzureMonitorAddonForSplunk#140]
I would like to have the dimensions for Key Vault and Storage Account resource metrics available.  Is this supported by the Azure Monitor Add-on for Splunk?

A similar issue was previously reported.
https://github.com/Microsoft/AzureMonitorAddonForSplunk/issues/74

**Comment by sebastus** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftstoragestorageaccounts


https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftkeyvaultvaults

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-logs-schema
(search
for keyvault / storage)

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-log-schema
(same
idea)

for metrics, you'll need to set up the metrics data input. don't send them
through an event hub.

**Comment by bdschaap** [comment]
Thanks I had previously configured the metrics to be ingested into Splunk.  It works great and I really like the feature.  However, I'm not seeing a breakdown by dimension for resources like Key Vault and Storage Accounts which have multi-dimensional metrics.  I wanted to get confirmation that it's not currently supported.

**Comment by sebastus** [comment]
did you tag the resources that you want to track? what specifically are you
not seeing?

fyi, lots of the storage analytics stuff is not routed through azure
monitor, but only via Storage Analytics
<https://docs.microsoft.com/en-us/azure/storage/common/storage-analytics>.
I'm not aware of any Splunk TA that processes storage analytics directly.
You may be able to use Splunk's MSCS TA (#3110 in splunkbase) but you'll
probably have to write some interesting queries. Storage Analytics are
implemented via azure table storage records.

**Comment by bdschaap** [comment]
Yes I tagged the resources using Metrics = * and am ingesting data into Splunk.  An example of the data I would like to include is the ActivityType dimension of the Total Service Api Results metric of the Key Vault resource.   Within Azure Monitor I am able to get a breakdowns such as counts for the vault, secret, and key activity types.  However, I don't appear to be getting it broken out by each activity type for this add-on.

**Comment by bdschaap** [comment]
Also, I'm able to retrieve storage metrics using the add-on though many of the events ingested don't actually contain data.  Events are recorded every minute but only those every hour (sometimes every other hour) actually have a metric value.  This seems to be the case for Key Vault as well except events that actually have a metric value are recorded every 45 minutes (but sometimes every 1.5 hours).  This is very strange behavior.  App Service events are also recorded every minute but always seem to contain data.  It's odd that App Service always has events with metric values but storage account and key vault usually doesn't and the interval that it actually contains data varies them.

I'm familiar with storage analytics and am anticipating that Microsoft will eventually make the approach to storing and retrieving this information similar to other Azure resources.  Many other Azure resources seem to be using the same approach of diagnostic settings that can route to a storage account, event hub, or Log Analytics.

**Comment by sebastus** [comment]
can you see the metrics that you're interested in in the portal with the
frequency that's missing in the add-on output?

just so you know, the add-on doesn't do anything at all to the data it gets
from the metrics endpoint. it just grabs it and shoves it into Splunk. if
the metric isn't reported then there's nothing to report. ;)

**Comment by bdschaap** [comment]
It doesn't quite match what the portal shows.  For instance, in Splunk I see a ServiceApiResult event have have a data.average value of 1.0 at 20:19:00Z and different ServiceApiResult event have a data.count value of 3.0 at 20:04:00Z.  However, within the portal I'm able to see both data points using either the Average aggregation or Count aggregation.

Thanks for the explanation on how the add-on works.

**Comment by bdschaap** [comment]
Also, I'm thinking that perhaps instead of recording the events that don't have data values to Splunk that it should filter those out.

**Comment by bdschaap** [comment]
I'm not familiar with the code base but suspect that splitting by dimension values is not supported in the add-on at this time.  I see that it is possible to accomplish this using the Azure Monitor REST API by specifying the $filter parameter.  In their example, specifying APIName eq '*' will cause the results to split by APIName and returns values for each individual APIName.  If the $filter parameter is unspecified then it returns rolled up values for all APINames.  It would be nice to be able to support multiple dimensions at some point down the road.

[Retrieve Metric Values](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/rest-api-walkthrough#retrieve-metric-values-multi-dimensional-api)
[URI Parameters](https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list#uri-parameters)

Also, I moved my second issue to [issue 141](https://github.com/microsoft/AzureMonitorAddonForSplunk/issues/141).
