### ISSUE TITLE
Graph API - > eventhub - amqp:unauthorized-acces

### ISSUE THREAD

**Issue by karenmcauley** [microsoft/AzureMonitorAddonForSplunk#142]
Hi,

We are trying to onboard security alerts from the graph api -> eventhub -> splunk.  We are following the steps outlined here:
https://docs.microsoft.com/en-us/graph/security-splunk-siemintegration

We have tried this twice now and get the same error message:

05-09-2019 15:04:01.917 -0400 ERROR ExecProcessor - message from ""C:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_diagnostic_logs.cmd"" Modular input azure_diagnostic_logs://AzureGraphDiagnosticsInput ==> RX ERROR on hub: insights-logs-alert, err: AmqpProtocolError: amqp:unauthorized-access:An AMQP error occurred (condition='amqp:unauthorized-access'). TrackingId:54358ab25e1e416a9ae5d5fd941e38d9_G31, SystemTracker:gateway5, Timestamp:2019-05-09T19:03:59

Your help is appreciated.

Thanks

Karen

**Comment by sebastus** [comment]
can you send me a screen shot of the key vault secret that you created?

**Comment by karenmcauley** [comment]
<img width="945" alt="Screen Shot 2019-05-09 at 20 45 36" src="https://user-images.githubusercontent.com/18612708/57482347-4fc0a280-729c-11e9-8879-ed31015c6c56.png">

**Comment by sebastus** [comment]
can I see the secret itself? you can obscure the actual details, but I'd
like to see the pane with the various secret properties.

**Comment by karenmcauley** [comment]
We have it running.  The  instructions did not specify when adding the secret value in the vault to specify content type of RootManageSharedAccessKey.  The content type field says "optional".  Once that was updated, the logs are now coming in. Is this required for access to event hubs and if so should those instructions be updated?

Thanks for your prompt response.

Karen

**Comment by sebastus** [comment]
Yes, the content type is not optional for the TA to work correctly. It's
only optional for the generic secret. Congrats on figuring it out. :)
