### ISSUE TITLE
Several Errors after configuration

### ISSUE THREAD

**Issue by max-we7** [microsoft/AzureMonitorAddonForSplunk#145]
Hi,

I'm getting several errors after installing the AddOn and configuring the inputs.
Could someone point me in the right direction as to where I might find the issue?

These are the errors in splunkd.log, there are no events leaving the event hub:

- ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure Monitor Activity Log Error 401 in the password waterfall: {1}

- … Modular input azure_activity_log://Azure Monitor Activity Log Error creating storage passwords: 

- … Modular input azure_activity_log://Azure Monitor Activity Log Error getting secrets from storagePasswords:

I'm also getting an SSL error:  Socket error from x.x.x.x:60464 while idling: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

Thanks for any tips!

**Comment by sebastus** [comment]
This may have to do with the service principal credentials supplied in the
configuration of the Activity Log data input. It must be able to read your
key vault secret. You can test this using the az cli. The secret in key
vault must contain the connection information for the event hub targeted by
Activity Logs - the one you exported to in the portal. The 'content type'
of the secret must name the access policy. I usually use
'RootManageSharedAccessKey', but that may be too permissive for your needs.
