### ISSUE TITLE
Error after configuration!

### ISSUE THREAD

**Issue by Askeens** [microsoft/AzureMonitorAddonForSplunk#146]
Hello!

I just went through the configuration for Azure Monitor, set up an Activity log input and I'm receiving this error: 

06-03-2019 16:32:19.624 -0400 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure_Monitor_Activity_Log_Test Error getting event hub creds: RequestError: Error: getaddrinfo ENOTFOUND XXXXX.vault.azure.net XXXXXX.vault.azure.net:443

Has anyone seen this before?

**Comment by sebastus** [comment]
Name resolution? Does the splunk box have a clear path to the internet?
Does the key vault exist?
