### ISSUE TITLE
CIM Compliance

### ISSUE THREAD

**Issue by sbhuttan** [microsoft/AzureMonitorAddonForSplunk#147]
We are evaluating this addon for integrating Azure Monitor data to Splunk and could not find any details on CIM compliance. Do we have the details or is there a way to find out if this addon is CIM compliant (even better to know which version of CIM)? 

More details on CIM - https://docs.splunk.com/Documentation/CIM/4.13.0/User/Overview

**Comment by sebastus** [comment]
It is not CIM compliant.
