### ISSUE TITLE
ERROR ExecProcessor Unexpected end of JSON Input

### ISSUE THREAD

**Issue by elbrianmcdonald-dev** [microsoft/AzureMonitorAddonForSplunk#149]
Getting the following errors 
ERROR ExecProcessor - message from ""C:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_activity_log.cmd"" Modular input azure_activity_log://Azure_Activity_Event_Hub Error getting event hub creds: SyntaxError: Unexpected end of JSON input

no longer getting azure event logs. 
I have verified all of the configuration input parameters.

**Comment by sebastus** [comment]
try deleting and re-adding the data input configuration. it sounds like the json descriptor got corrupted.
