### ISSUE TITLE
version tag in app.conf

### ISSUE THREAD

**Issue by ramganesh19** [Microsoft/AzureMonitorAddonForSplunk#15]
Hi,

Can you please change the version tag to "major.minor.Revision" format. Since Splunk Cloud Ops team validation failed when trying to validate

Check :
Check that the extracted Splunk App contains a default/app.conf file that contains an [id] or [launcher] stanza with a version property that is formatted as Major.Minor.Revision.

Message:
Splunk App packages must contain a `default/app.conf file with an `[id]` or [launcher] stanza using the `version` property formatted as `Major.Minor.Revision`.

**Comment by sebastus** [comment]
I changed 1.2.3.1 -> 1.2.4. Sorry for the inconvenience.

**Comment by ramganesh19** [comment]
Hi Sebastus, We are not seeing the changes in the file Thx Ramg
