### ISSUE TITLE
ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by fredshino** [microsoft/AzureMonitorAddonForSplunk#150]
Any tips on how to troubleshoot the below error?

07-01-2019 17:31:56.033 -0400 FATAL ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"  1: node::Abort() [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"  2: 0xf43e9c [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"  3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"  5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"  6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"  7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"  8: v8::String::WriteUtf8(char*, int, int*, int) const [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh"  9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" 10: node::StreamBase::Writev(v8::FunctionCallbackInfo<v8::Value> const&) [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" 11: void node::StreamBase::JSMethod<node::StreamWrap, &node::StreamBase::Writev>(v8::FunctionCallbackInfo<v8::Value> const&) [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" 12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" 13: 0x84cb24 [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" 14: 0x84d20c [node]
07-01-2019 17:31:56.039 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" 15: 0xa5e896092a7
07-01-2019 17:31:56.246 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" /Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh: line 16: 20942 Aborted                 "$SPLUNK_HOME/bin/splunk" cmd node "$current_dir/app/azure_diagnostic_logs.js" $@

**Comment by sebastus** [comment]
What are the Azure resource types that you are monitoring? I recently discovered that monitoring a kubernetes cluster introduces some messages to diagnostics that don't match the usual schema. There could be others.

**Comment by fredshino** [comment]
I enabled Diagnostic Logs on every single resource type that supports it:
[https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-logs-schema](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-logs-schema)

What happens in this case? Does it discard only that specific message with the different schema? Will other messages be affected?

**Comment by sebastus** [comment]
Some recent additions to Azure Monitor supported resource types, such as
App Insights, don't conform to the previous standard message format. This
breaks the code. I have learned of a few of them and will be fixing the
code accordingly. I would appreciate help identifying any others that
similarly don't conform to expedite the process.

**Comment by Guitaraholic** [comment]
I know this is quite an old issue but wondering if this is still being kept 'open' for this to be looked at in the code? seeing this with NSG Record logs only and significant delays in the processing of the logs
