### ISSUE TITLE
BUG: Add-On won't save multiple sets of credentials

### ISSUE THREAD

**Issue by fredshino** [microsoft/AzureMonitorAddonForSplunk#151]
When creating a second input with a different set of credentials (different tenant ID, different App ID / secret), the add-on overwrites the existing set of credentials saved on /Data/splunk/etc/apps/TA-Azure_Monitor/local/passwords.conf instead of keeping multiple sets of credentials.

It's easy to reproduce:
1) Create input 1.
2) Input 1 starts working.
3) Create input 2, different tenant ID, appID, secret.
4) Input 2 starts working, input 1 breaks and the following error is thrown:
 06-28-2019 10:38:47.283 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://[**input 1**] Error getting event hub creds: Error: Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '[redacted]' was not found in the directory '[redacted]'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
5) Edit input 1 and update the credentials.
6) Input 1 starts working, input 2 breaks and the following error is thrown:
 06-28-2019 10:38:47.283 -0400 ERROR ExecProcessor - message from "/Data/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://[**input 2**] Error getting event hub creds: Error: Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '[redacted]' was not found in the directory '[redacted]'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by sebastus** [comment]
It's a design limitation. As you discovered, the add-on will only accept one set of data input definitions per data input type. You can install the add-on again with a different name if you need multiple. A better approach is to use the function. Azure Function for Splunk VS.

**Comment by fredshino** [comment]
If this is by design, then it needs to be better documented or handled by the code.

On step 3: Create input 2, different tenant ID, appID, secret; It should gray out the fields so the user isn't led to believe that he can use a different set of credentials there.

Don't you agree that it's currently misleading?
