### ISSUE TITLE
Unable to connect to EventHub for activity logs

### ISSUE THREAD

**Issue by nixonvarghese** [microsoft/AzureMonitorAddonForSplunk#153]
Hi There,

I have installed all the python and nodejs dependencies I assume and also configured the activity logs modular input. But it is unable to connect to eventhub  in azure. Getting the below error. 

07-29-2019 15:05:00.424 -0400 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://AzureActivityLogs_Splunk Error getting event hub creds: StatusCodeError: 404 - {"error":{"code":"SecretNotFound","message":"Secret not found: RootManageSharedAccessKey/*********************"}}

Additionally when I tried to telnet to 5671 and 5672 , didn't look like the service was running.  Any thoughts, suggestions, advice?

**Comment by sebastus** [comment]
it sounds like your key vault secret is not configured correctly. the ContentType value is the name of the policy (RootManageSharedAccessKey) and the secret value is the policy key.
