### ISSUE TITLE
Feature Request: Resource Name of child resources

### ISSUE THREAD

**Issue by trolleyboy** [microsoft/AzureMonitorAddonForSplunk#155]
Some Azure resources have parent resources, such as SQL Databases that have the SQL Server parent.  
When Metrics are pulled in for the child resource, in this example a SQL Database, the value of the amm_resourceName field is only the name of the parent SQL Server, not the child.  

I believe it would be beneficial to see something like SQLServerName/DatabaseName as the amm_resourceName value.

**Comment by sebastus** [comment]
yes, there are a few resources like this. I'll take a look.

**Comment by trolleyboy** [comment]
Another parent/child resource I've found with this issue is App Service deployment slots.  Metrics for the Slot are loaded into Splunk with amm_resourceName being the parent App Service name.
