### ISSUE TITLE
ERROR: Unable to get event hub creds: Unauthorized, Invalid Issuer

### ISSUE THREAD

**Issue by riflesux** [microsoft/AzureMonitorAddonForSplunk#159]
I've configured the Add-on per instructions, and configured an input for Activity Logs, but I'm not getting any data. I checked the splunkd.log and saw the following error:

`08-23-2019 13:49:28.720 -0700 ERROR ExecProcessor - message from ""C:\Program Files\Splunk\etc\apps\TA-Azure_Monitor\bin\azure_activity_log.cmd"" Modular input azure_activity_log:// AzureActivityLogs Error getting event hub creds: StatusCodeError: 401 - {"error":{"code":"Unauthorized","message":"AKV10032: Invalid issuer. Expected one of https://sts.windows.net/[redactedSubscription/TenantID?]/, https://sts.windows.net/[redactedSubscription/TenantID?]/, https://sts.windows.net/[redactedSubscription/TenantID?]/, found https://sts.windows.net/[redactedMyAzureADTenantID/."}}`

The 3 listed as "expected" show what appear to be subscription or tenant IDs, but I don't recognize them, and cannot find any matches in my Azure environment. The "found" address is my TenantID, taken directly from Azure AD where my app is located. I've looked through all the issues here, as well as on Splunk Answers, and haven't been able to find anything specific to this error.

**Comment by sebastus** [comment]
Hi @riflesux. Please contact me directly: golive@microsoft.com
