### ISSUE TITLE
Packaging script does not preserve POSIX permissions on *nix

### ISSUE THREAD

**Issue by jsrobards** [microsoft/AzureMonitorAddonForSplunk#167]
It looks like 7zip, which is used in the current package.sh script that creates the app's spl archive, does not preserve POSIX permissions. This creates a security issue on *nix operating systems as the files are unarchived with 777 permissions.

This means the code Splunk will execute while running the TA is writable by any user on the server. They could inject code into the TA which Splunk will run with whatever permissions splunkd is running with. 

In the version of Splunk I have installed the parent folder for the TA ($SPLUNK_HOME/etc/apps) is not globally traversable (drwxr-x---) and that mitigates the issue somewhat. But I would not depend on that as a control.

I've put in a pull request that allows package.sh to use either 7z or tar. I advise that we remove the 7z dependency entirely in that script and just use tar.

#166

**Comment by sebastus** [comment]
Thanks, jsrobards. I'll take a look.

**Comment by sebastus** [comment]
Handled in recent PR
