### ISSUE TITLE
am_depends_rhel.sh execution python dependencies errors

### ISSUE THREAD

**Issue by bikashkarmakar** [microsoft/AzureMonitorAddonForSplunk#170]
Hi , 
We tried to execute am_depends_rhel.sh on a CentOS but got the below errors 

ERROR: rtslib-fb 2.1.69 has requirement pyudev>=0.16.1, but you'll have pyudev 0.15 which is incompatible.
ERROR: ipapython 4.6.5 has requirement dnspython>=1.15, but you'll have dnspython 1.12.0 which is incompatible.
ERROR: ipapython 4.6.5 has requirement python-ldap>=3.0.0b1, but you'll have python-ldap 2.4.15 which is incompatible.

Any pointers is greatly appreciated ?

**Comment by sebastus** [comment]
The rhel version of am_depends is probably the least tested. My
recommendation would be to run through the dependency installation manually
given the information in the docs. If you want to submit a PR to update the
am_depends, that would be great.

Cheers!
Greg
