### ISSUE TITLE
Azure China Diagnostics error No connection on hub: docs05. Is there a network route to the endpoint?

### ISSUE THREAD

**Issue by bikashkarmakar** [microsoft/AzureMonitorAddonForSplunk#171]
We are trying to get the AzureMonitorAddonForSplunk configured too AzureChina. We are getting the below errors

ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" Modular input azure_diagnostic_logs:// SplunkAzureMonitor2 No connection on hub: docs05. Is there a network route to the endpoint?

The AzureChina cloud is configured in azure_diagnostic_logs.sh and we can get the activity logs ok from AzureChina but not the diagnostics log.

Any pointers is great appreciated.

**Comment by sebastus** [comment]
Great to hear that you have it working in the China DC.

re: diagnostics. look into hubs.json. It should contain a record for each
hub that exists in the hub namespace and that is receiving telemetry from
Azure Monitor. It should contain no other records.
