### ISSUE TITLE
 Data forwarding issue from eventhub

### ISSUE THREAD

**Issue by monicapandrakula** [microsoft/AzureMonitorAddonForSplunk#173]
We are having trouble with getting the data from the event hub. We get the data by the addon installed on our heavy forwarder.

ADD ON - Azure Monitor Add on For Splunk

We need support for the add on issue.

**Comment by sebastus** [comment]
Symptoms?

**Comment by monicapandrakula** [comment]
we get the data for metrics logs but no logs observed for diagnostic logs or activity logs

**Comment by brettwilliams101** [comment]
@sebastus we are seeing the same.  We stopped receiving diagnostic logs over the weekend.
