### ISSUE TITLE
Unable to initialize modular input "azure_monitor_metrics" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_monitor_metrics: script running failed (exited with code 1

### ISSUE THREAD

**Issue by mpras123** [microsoft/AzureMonitorAddonForSplunk#174]
I am running into this with Azure Monitor app.
Unable to initialize modular input "azure_monitor_metrics" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_monitor_metrics: script running failed (exited with code 1

Splunk is on windows -
Splunk Enterprise : Version:7.1.3
Python 3.8.1
Node js: 12.16.1

followed the steps defined for windows  here - https://github.com/microsoft/AzureMonitorAddonForSplunk/wiki/Installation-on-Windows

any help is really appreciated.
Regards,
Prasad

**Comment by sebastus** [comment]
50% of the time metrics fails because of configuration. The other 50% is
because dependencies aren't installed correctly.

Configuration is confusing - mainly because key vault contains the
credentials that run the ARM api that gets the metrics. The splunk
configuration points to the key vault secret that contains the credentials.

**Comment by mpras123** [comment]
i haven't gotten that far, the app doesn't even open the data inputs configuration, should be dependencies installation issue??

**Comment by chrismewett** [comment]
This may be related to an issue with splunk-sdk 1.6.12 - i was able to resolve this by running the following on Linux - change paths as appropriate for Windows:
`pip install 'splunk-sdk<1.6.12' -t $SPLUNK_HOME/etc/apps/TA-Azure_Monitor/bin --upgrade
pip install 'splunk-sdk<1.6.12' -t $SPLUNK_HOME/etc/apps/TA-Azure_Monitor/bin/app --upgrade
`
