### ISSUE TITLE
Do values for SPNApplicationKey, eventHubNamespace, vaultName, secretName, secretVersion have to be changed regularly?

### ISSUE THREAD

**Issue by mike1li** [microsoft/AzureMonitorAddonForSplunk#175]
I've finally completed the steps to get the SPNTenantID, SPNApplicationId, SPNApplicationKey, eventHubNamespace, vaultName, secretName, secretVersion which I configured for Azure Monitor Activity Log and Azure Monitor Diagnostic Logs but getting creds errors
How long is the SPNApplicationKey, eventHubNamespace, vaultName, secretName, secretVersion be used for? Do they need to be regularly updated for Azure Monitor Activity Log and Azure Monitor Diagnostic Logs? It seem that when run ./azure-setup.sh -r Splunk-Azure-Integration -l eastus -t tenantid -s subscriptionid, the values for SPNApplicationKey, eventHubNamespace, vaultName, secretName, secretVersion change and have to be updated in input settings for Azure Monitor Activity Log and Azure Monitor Diagnostic Logs
 Please advise. Thanks.
Mike
--logs of creds issue---
ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://AzureActivityLog Error getting event hub creds: Error: Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: a7dcca71-0588-4c72-9a0c-7140026a0f00\r\nCorrelation ID: d1b0c221-12c9-42c2-96e4-bbba2eb441f0\r\nTimestamp: 2020-03-23 12:55:56Z","error_codes":[7000215],"timestamp":"2020-03-23 12:55:56Z","trace_id":"a7dcca71-0588-4c72-9a0c-7140026a0f00","correlation_id":"d1b0c221-12c9-42c2-96e4-bbba2eb441f0","error_uri":"https://login.microsoftonline.com/error?code=7000215"}

**Comment by brettwilliams101** [comment]
I'm curious to know this answer as well.  Our diagnostic logs stopped coming into Splunk a few days ago.
