### ISSUE TITLE
Azure Monitor Hub Configuration Support

### ISSUE THREAD

**Issue by andredvice** [microsoft/AzureMonitorAddonForSplunk#178]
Installed Azure Monitor Add-on version 1.3.3 on Windows Server 2012 R2 with the following dependencies:
1) Python 2.7.12
2) NodeJS 12.16.2

Upon review of the debug logs within Splunkd.log, I noticed the following error:

" Modular input azure_activity_log://Azure Activity Log ==> Did not find hub: insights-operational-logs. Message: amqp:not-found:The messaging entity 'sb://eventhubspace-core-corp-use1.servicebus.windows.net/insights-operational-logs/consumergroups/$default/partitions/0' could not be found."

The hub "insights-operational-logs" appears to be built into the pluggin. Is this configurable? Can the activity, diagnostics, and metrics be sent to one hub?

**Comment by tangojx3** [comment]
See the hubs.json file in this wiki link. 
https://github.com/microsoft/AzureMonitorAddonForSplunk/wiki/Configuration-of-Splunk

It should help your question.
