### ISSUE TITLE
bin/app/logCategories.json  not using resourceType to look up diagnostic logs sourcetype

### ISSUE THREAD

**Issue by neilbattersby** [Microsoft/AzureMonitorAddonForSplunk#18]
function getAMDLsourcetype(category, resourceType) in bin/app/azure_monitor_logs.js  sets the sourcetype by looking up the resourceType + category  in  bin/app/logCategories.json.   resourceType is parsed from resourceID by the line -
var resourceType = getElement(resourceId, 'PROVIDERS\/(?:.*?\/.*?\/)(.*?)(?:\/|$)');

So for resourceId:	 /SUBSCRIPTIONS/A3B88F73-897A-45D9-BFFB-0572A0888656/RESOURCEGROUPS/DEV-DEMO/PROVIDERS/MICROSOFT.NETWORK/LOADBALANCERS/DEV-DEMO	
and category: LoadBalancerProbeHealthStatus	
we have resourceType + category = DEV-DEMO + LoadBalancerProbeHealthStatus
This does not match the -
 "MICROSOFT.NETWORK/LOADBALANCERS/LOADBALANCERPROBEHEALTHSTATUS":"amdl:net:lb:probeHealth",  
- line in bin/app/logCategories.json.

Shouldn't     bin/app/azure_monitor_logs.js parse the resourceType by using 
var resourceType = getElement(resourceId, 'PROVIDERS\/(.*?\/.*?)(?:\/)');
So for that for resourceId:	 /SUBSCRIPTIONS/A3B88F73-897A-45D9-BFFB-0572A0888656/RESOURCEGROUPS/DEV-DEMO/PROVIDERS/MICROSOFT.NETWORK/LOADBALANCERS/DEV-DEMO	
and category: LoadBalancerProbeHealthStatus	
we have resourceType + category = MICROSOFT.NETWORK/LOADBALANCERS  + LoadBalancerProbeHealthStatus
Which matches the - 
 "MICROSOFT.NETWORK/LOADBALANCERS/LOADBALANCERPROBEHEALTHSTATUS":"amdl:net:lb:probeHealth",   
- line in bin/app/logCategories.json and sets te sourcteype to amdl:net:lb:probeHealth

**Comment by sebastus** [comment]
@neilbattersby thanks for pointing this out. The error was introduced on Oct 28, 2017. It will be fixed shortly.
