### ISSUE TITLE
this has been forked and isnt really supported here anymore

### ISSUE THREAD

**Issue by mary-cordova** [microsoft/AzureMonitorAddonForSplunk#21]
https://github.com/rickrain/AzureMonitorAddonForSplunk

**Comment by automine** [comment]
Just a head's up, you may want to update the link provided here: https://splunkbase.splunk.com/app/3534/

**Comment by mary-cordova** [comment]
Yeah it would be great if Splunk actually managed data inputs...

**Comment by automine** [comment]
Hey @mary-cordova, I don't work for Splunk, but I would like to help. I'm not sure what you mean by that statement, can you explain what kind of management you mean?
