### ISSUE TITLE
Unable to get Azure Activity Log integration working 

### ISSUE THREAD

**Issue by mroyster** [microsoft/AzureMonitorAddonForSplunk#30]
I just cannot get this working, I believe I have followed all the steps and have checked 2-3 times but getting following errors in the splunk log. Any pointers welcome to diagnose and fix this. It looks the similar error to others are experiencing. 

04-22-2018 18:01:35.314 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     import splunklib.client as client
04-22-2018 18:01:35.314 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" ImportError: No module named splunklib.client
04-22-2018 18:01:35.502 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://mroystersubsciption Error getting event hub creds: StatusCodeError: 403 - {"error":{"code":"Forbidden","message":"Access denied","innererror":{"code":"AccessDenied"}}}
04-22-2018 18:02:35.308 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"   File "mask_secret.py", line 31, in <module>
04-22-2018 18:02:35.309 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     import splunklib.client as client
04-22-2018 18:02:35.309 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" ImportError: No module named splunklib.client
04-22-2018 18:02:35.584 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://mroystersubsciption Error getting event hub creds: StatusCodeError: 403 - {"error":{"code":"Forbidden","message":"Access denied","innererror":{"code":"AccessDenied"}}}
04-22-2018 18:03:35.354 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"   File "mask_secret.py", line 31, in <module>
04-22-2018 18:03:35.354 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     import splunklib.client as client
04-22-2018 18:03:35.354 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" ImportError: No module named splunklib.client
04-22-2018 18:03:35.613 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://mroystersubsciption Error getting event hub creds: StatusCodeError: 403 - {"error":{"code":"Forbidden","message":"Access denied","innererror":{"code":"AccessDenied"}}}

**Comment by secops4thewin** [comment]
Hey mroyster check my comment on another thread “The problem seems to be related to splunklib not being available in your python sitepackages folder. Can you do an 'ls' in your 'dist-packages and 'site-packages' folder of python and paste it here.”

**Comment by sebastus** [comment]
@mroyster and I discovered a workaround: copy the splunklib folder from bin to bin/app. This isn't a solution - I'm not sure yet why this problem exists. But the workaround gets us past the ImportError.
