### ISSUE TITLE
Unable to get Azure Activity Log, Azure Diagnostic Logs and Metrics

### ISSUE THREAD

**Issue by artemisa05** [microsoft/AzureMonitorAddonForSplunk#32]
Hi, it has been detected problems when it comes to communicating azure with the splunk tool, I have already configured azure and splunk, but they fail to connect, it gives the several errors, for example:

- ERROR ExecProcessor - message from 'python //$SPLUNK_HOME/TA-Azure_Monitor/bin/azure_monitor_metrics.py' Error caught in get_metrics_for_subscription, type: <class 'adal.adal_error.AdalError'>, value: Get Token request returned http error: 400 [Problem start date and time].

Has anybody solve this?.

**Comment by sebastus** [comment]
@artemisa05 this points to a problem with the credentials for getting metrics. It also requires that you create a service principal with the reader rights for the ARM apis in your subscription(s). You can test your service principal with a tool like Postman. If you can get a security token and then execute one of the GET apis, then the service principal is correct.
