### ISSUE TITLE
Unable to use proxy with the Addon

### ISSUE THREAD

**Issue by nikhilv14** [microsoft/AzureMonitorAddonForSplunk#33]
In the environment, access to Azure is only allowed via proxy. I have configured proxy settings in Splunk's server.conf, however, the addon is trying to contact directly to key-vault. Can you please elaborate on configuring proxy with the addon?

**Comment by sebastus** [comment]
@nikhilv14 I assume you mean your on premises environment. Most (if not all) Azure services (such as key vault) do not have static IPs that you can plug into your proxy servers. To use the add-on on-premises, you need to establish a VPN or ExpressRoute to Azure, then route traffic through that link. An alternative is to use a forwarder in Azure to collect the telemetry from Azure-based resources and send them to your on prem Splunk Enterprise / indexer/query heads.

**Comment by brettwilliams101** [comment]
Hi @sebastus ... any plans to add proxy support?  Or is this reliant on a direct TCP connection?  Seems under the hood it's using AMQP.

**Comment by sebastus** [comment]
It requires a static IP address on the key vault and event hub end of
things, which doesn't exist.

For Splunk on prem, the Azure Function is a better approach.

https://github.com/Microsoft/AzureFunctionforSplunkVS

See parts 4 and 5 of this blog series:
https://blogs.msdn.microsoft.com/golive/2017/04/17/send-telemetry-to-splunk-enterprise-from-azure-resources-via-azure-monitor/

**Comment by brettwilliams101** [comment]
So I have learned that we can open firewall based upon FQDN.  Looking at [this file](https://github.com/Microsoft/AzureMonitorAddonForSplunk/blob/master/bin/app/environments.json), the hosts I need to open for _AzureCloud_ are:

- login.microsoftonline.com
- vault.azure.net
- servicebus.windows.net

Is that all?  I didn't have a chance go poke through all the scripts.

**Comment by brettwilliams101** [comment]
@sebastus, could you reply to my previous comment?  We have firewalls which can allow outbound connection based upon hostname, not IP, so a static IP isn't a problem for us.

I looked at the Azure Function, but that requires an inbound connection to HEC (which we would run on-premise).  We can't swing that without dual factor (SSL cert is considered single factor, and the list of acceptable additional factors is not something we could do with Splulnk HEC alone) or a red-tape-laden security risk exception.  And we aren't yet positioned to run VMs in Azure.

**Comment by sebastus** [comment]
re: endpoints. I think that's everything, unless you also plan to run in
one of the sovereign data centers (like us government, china, etc). Check
bin/app/environments.json for the details. I'm not 100% sure if you're
using MSI authentication. There's another library called (msRestAzure) that
might call https://management.core.windows.net.

re: servicebus.windows.net, I assume you know that your hub namespace will
be prepended.

re: function. What about this architecture:
https://blogs.msdn.microsoft.com/golive/2017/07/08/send-telemetry-to-splunk-enterprise-from-azure-resources-via-azure-monitor-part-5/
?

**Comment by brettwilliams101** [comment]
I didn't know that.  Thanks for pointing that out.  :)  I imagine my Azure architect/owner will know that information.  

So Azure Function is serverless...  that might be doable.

As far as firewall ports go...  443 is all I've opened so far.  Are there more I should know about?

**Comment by sebastus** [comment]
re: firewall ports. Yes, that's the only one.
