### ISSUE TITLE
Error Getting EventHubs

### ISSUE THREAD

**Issue by bharathkumarnec** [microsoft/AzureMonitorAddonForSplunk#36]
Hi Team,

We are getting below error:
/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" Modular input azure_diagnostic_logs://AzureDiagnosticLogDetails Error getting event hub creds: Error: getaddrinfo ENOTFOUND login.microsoftonline.com login.microsoftonline.com:443

Is this related to credentials or network?

Regards,
BK

**Comment by sebastus** [comment]
@bharathkumarnec If I had to guess, I would say it's a network issue. It seems to be saying that it can't reach that address. You should be able to test it with a browser. https://login.microsoftonline.com is a very well-known address.
