### ISSUE TITLE
ERROR Modular input Error

### ISSUE THREAD

**Issue by bharathkumarnec** [microsoft/AzureMonitorAddonForSplunk#37]
Hi Team,
We are receiving below errors with this add on in our environment:
ioctl(0, TCGETS, 0x7ffd6514efe0)        = -1 ENOTTY (Inappropriate ioctl for device)
write(2, "ERROR Modular input Error: Recei"..., 85ERROR Modular input Error: Receiving input definitions prior to streaming timed out.

Kindly help us with this to get this resolved.

Regards,
BK

**Comment by bharathkumarnec** [comment]
Hi Mickey,
Here is the linux version Linux 3.10.0-693.21.1.el7.x86_64
Regards,
BK

**Comment by secops4thewin** [comment]
Are you using SELinux by any chance?

**Comment by bharathkumarnec** [comment]
Yes!

**Comment by secops4thewin** [comment]
My guess is SELinux is blocking something throughout the request :).

**Comment by bharathkumarnec** [comment]
I tried disabling the SELinux, but no luck!
