### ISSUE TITLE
AppID and AppKey overwritten when adding multiple subscriptions

### ISSUE THREAD

**Issue by andryr3a** [microsoft/AzureMonitorAddonForSplunk#39]
As discussed with @rickrain over the phone, the SPN AppID and AppKey is overwritten every time a new subscription is added. Those two fields are obfuscated in JS according to Rick and don't handle multiple input stanzas.
Consider using Splunk's built in password store. This is a great read and should point you guys in the right direction: [http://www.georgestarcher.com/splunk-stored-encrypted-credentials/](http://www.georgestarcher.com/splunk-stored-encrypted-credentials/) . Also
[a blog entry from Splunk](https://www.splunk.com/blog/2015/10/20/securely-storing-accessing-passwords-for-alert-action-scripts.html)

**Comment by sebastus** [comment]
@andryr3a Thanks for the feedback, Andry.

**Comment by emacintosh** [comment]
I just ran into this issue today with diagnostic logs.  Created a new input which overwrote the appID and appKey for the existing input...which of course that broke that input.  We're being asked to create input for at least 3 new tenants, so this issue will be a blocker.

I'm on version 1.2.9

**Comment by sebastus** [comment]
@emacintosh Thanks for the feedback. This is a good time to start to work on it. What's your timeline?

**Comment by emacintosh** [comment]
Great to hear @sebastus  We currently have requests in our queue for this functionality.  We typically provide a turnaround time of a month.  Is that doable?

**Comment by sebastus** [comment]
@emacintosh Please take a look at version 1.3.0. We added the ability to use MSI credentials instead of service principal. I think it'll solve your problem. Please let us know what you fine.

**Comment by emacintosh** [comment]
@sebastus I'm getting an error on upgrade and fresh install.  We're running 7.0.4 on RHEL 6.9.

> Unable to initialize modular input "azure_monitor_metrics" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_monitor_metrics: script running failed (exited with code 1).

I'll check the logs...

**Comment by sebastus** [comment]
There's another package to install with v1.3.0+ relative to v1.2.9. Check
the python and node.js packages in the am_depends for ubuntu to see which
ones. I'm not sure the RHEL am_depends was updated.

**Comment by emacintosh** [comment]
@sebastus Is it the Markdown package?  Getting additional packages installed into our environment isn't a simple process, but I can work on it.  I just want to be sure I'm working on the correct one.

Is there any chance that future releases won't be introducing further packages?  This is by far the most work we have to do for any splunk add-ons.

**Comment by sebastus** [comment]
No - it's a python library. MS Rest Azure, to be specific. If you look in the am_depends scripts (in the packages folder) you'll see it.

I wish it were possible to include the packages in the installation. My legal won't permit it. So sorry for the inconvenience. :(

**Comment by emacintosh** [comment]
Any chance that Splunk will take this over some day?  Because if the upgrades are going to be this involved, we may start looking for other solutions.

I'm sure I'm doing something wrong, but i installed msrestazure python module.  I then copied over all of the packages that came with it to the bin directory.  Still got the error.

Based on the output of manually running the metrics script, I also copied urllib3, chardet, certifi, idna and enum to the app's bin directory.  That finally fixed the load error for metrics

But now diagnostics won't load.  And it seems like i need to install the ms-rest-azure node module now too?  Which i tried to, but seemed to get a CERT_UNTRUSTED error.

I'm going to set this down for a bit as i wrap up a few other projects before splunk's conf next week.

**Comment by sebastus** [comment]
You're almost there.

The log data inputs depend on Node.js. See here:

https://github.com/Microsoft/AzureMonitorAddonForSplunk/wiki/Installation-on-Linux#nodejs-dependencies

**Comment by emacintosh** [comment]
well i think the original node.js module are still there - it's just that i'm specifically missing the ms-rest_azure one.  So tried running "npm install ms-rest-azure" which resulted in the CERT_UNTRUSTED error.

Do i just re-run npm install with no parameters instead?

**Comment by sebastus** [comment]
Oh - I thought you had not yet run 'npm install'. You shouldn't have to run it twice. ms-rest-azure is not used by the node.js side of things. What's the error code you're getting? a 1 or a 127, or...?

**Comment by emacintosh** [comment]
Sorry...caught got up with some other things.  If i try to run the azure_diagnostic_logs.sh manually, i get the following message. 

Error: Cannot find module 'ms-rest-azure'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tools/splunk/etc/apps/TA-Azure_Monitor/bin/app/subs.js:37:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tools/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_monitor_logs.js:42:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /tools/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_diagnostic_logs.js:34:16
    at Object.<anonymous> (/tools/splunk/etc/apps/TA-Azure_Monitor/bin/app/azure_diagnostic_logs.js:70:3)

**Comment by sebastus** [comment]
Add ms-rest-azure to packages. Json
Npm install

**Comment by emacintosh** [comment]
it was already in the json so re-ran npm install.  But i'm still getting the cert error.  I'll revisit this after conf

npm WARN package.json azure_monitor@1.3.0 No repository field.
npm WARN package.json azure_monitor@1.3.0 No README data
npm http GET https://registry.npmjs.org/ms-rest-azure
npm http GET https://registry.npmjs.org/ms-rest-azure
npm http GET https://registry.npmjs.org/ms-rest-azure
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1430:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:1029:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:521:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:418:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

**Comment by sebastus** [comment]
Your system does not trust npm's cert. Can you fix? Nothing to do with the
add-on.

**Comment by bdschaap** [comment]
Do you know when this will be fixed?

**Comment by sebastus** [comment]
It's not exactly broken - working as originally designed. There have been
several requests for the functionality. My current job responsibilities
make it impossible for me to prioritise the work. I'm happy to vet a PR if
someone else in the community can do the programming and testing.

Cheers!
Greg
