### ISSUE TITLE
EventHub data flow stopping after view minutes

### ISSUE THREAD

**Issue by ViGblS** [microsoft/AzureMonitorAddonForSplunk#40]
In general this plugin is working properly, but unfortunately we have problems getting metric data from EventHubs (all other resources are working fine).
So it's not a general problem.

The EventHub is tagged with'Metrics: SuccessfulRequests, ServerErrors, UserErrors, QuotaExceededErrors, ThrottledRequests, IncomingRequests, IncomingMessages, OutgoingMessages, INREQS, SUCCREQ, FAILREQ, SVRBSY, INTERR, MISCERR, EHINMSGS, EHOUTMSGS, EHAMSGS'.

After tag is defined, the metrics are recorded/delivered for about 10 minutes. The data stream is interrupted without any error message. Server logging of the execProcessor is already set to'debug'.
Any tips I can get to the bottom of? Is it perhaps more due to Microsoft? But how can I analyze that?

When the day is updated, data is recorded again for about 10 minutes...

**Comment by sebastus** [comment]
The add-on wants to see the metrics coming from the ARM api. It doesn't
listen to an Event Hub for metrics. As far as the add-on is concerned,
Event Hubs is only a source of logs, such as Activity Logs and Diagnostic
Logs. This is for historical reasons - when the add-on was written, metrics
were only available via api.

Each resource has its own set of metrics. You need to tag each resource
with the appropriate tags for that resource. Tagging the event hub only
tells the add-on which metrics to collect for that event hub (metrics
relevant to the operation of the event hub itself).

It might be easiest to tag all relevant resources with Metrics=* to start
with, then pare back the ones that are reporting too much. The best way to
do this is with a PowerShell script or similar.

If you have only tagged an event hub, then only metrics relevant to that
event hub will report. There's probably not much to report on an ongoing
basis for an event hub.

**Comment by RalfWenzel** [comment]
@sebastus, i am a colleague of @ViGblS and started working on this issue also. By reading you comment above i've got the feeling that some clarification is required:

- Your paragraph "The add-on ..." : This is clear to us.
- Your paragraph "Each resource..." : Our Enduser services running on Azure make extensive usage of AMQP protocol for data interchange. So we are really interested in "metrics relevant to the operation of the event hub itself" to put it in your words. We got a bunch of EventHubs,  spread over some subscriptions. 
- We tag the EH-Namespaces we are interested in, e.g. "Metrics: SuccessfulRequests, ServerErrors, UserErrors, QuotaExceededErrors, ThrottledRequests, IncomingRequests, IncomingMessages, OutgoingMessages, INREQS, SUCCREQ, FAILREQ, SVRBSY, INTERR, MISCERR,EHINMSGS,EHOUTMSGS,EHAMSGS"

After tagging an EH-Namespace resource, everything looks fine for a while. The add-on delivers metric values as expected and we can search/find them in splunk. But after some (~10) minutes the add-on stops delivering values. So we have metrics only for ~10 minutes after tagging the resource.

Now: When we change the tag value on the resource, e.g. remove or add a metric-name from the list, the add-on starts delivering data again. But again only for ~10 minutes. This can be reproduced.

Note: We see this behaviour only on "Microsoft.EventHub/namespaces" type of resources. On other resource types, the add-on works as expected.

I'll dig a little deeper today and add more info's.

**Comment by sebastus** [comment]
I think I understand better now - you are interested in monitoring the Event Hubs and you are using the ARM api to gain access to the metrics. The metrics are flowing for about 10 minutes and then stopping. If you change the tags, metrics report again for about 10 minutes and then stop.

The add-on remembers the list of available metrics by resource type in bin/metricDefinitions.json. It compiles this list any time it checks the file for a resource type and finds no list. On each invocation, the add-on compares the list of metrics in tags with this list of available metrics and requests the intersection of these two sets from the platform. 

How often does the add-on run? On my test systems, I run it each minute. Can you try with Metrics: *, just to see if the behavior changes? Can you switch on debug logging to see what information that might add? I'm curious if it just stops checking the eh's or if there's some error condition cropping up.

**Comment by RalfWenzel** [comment]
- Yes, correct understanding now.
- Add-On is started once per minute, as on your test system
- debug logging is on.
- I removed "Metrics"-Tag from all but one EventHub to reduce debug output and to exclude that problem is cause by the number of EH's we monitor.
- On the EH left, i'm switching between to metrics without dimensions (INREQS or SUCCREQ) to trigger the whole process

This was the most simple setup i could think of, but problem still there. I'll try the "Metrics: *" later as you proposed, i'll have a look at the code first. 

Just to mention that: We are monitoring resources in 5 subscriptions. I don't know how the scheduler for the add-on works and if py script is run sequentially for each subscription or if multiple instances are run in parallel. I don't suspect something here,  just a comment to think about.

I'll add my findings when i found my way through the log output.

**Comment by RalfWenzel** [comment]
@sebastus, i dblchecked that there were no errors in logs when metrics stop after 10 minutes. I noticed 
that the debug message "'getting list of metrics for: {0}'" does not show up anymore in the logs for the EH resource after this situation. The message is written in function 'get_index_resource_metrics' in subs.py. But in the fuction i could not find any problem on first view. Is it possible that the code block below from function 'get_metrics_for_resources' causes the problem? 

 with futures.ThreadPoolExecutor(max_workers=5) as executor:
        metrics_future = dict((executor.submit(
            get_index_resource_metrics, ew, bearer_token, sub_url, rq, input_sourcetype, checkpoint_dict), rq)
            for rq in list_of_requested_metrics)

**Comment by sebastus** [comment]
The line of code that I suspect is 248 - it returns from the function with an empty set if there are no available metrics for the resource. Can you check the contents of metricDefinitions.json for the event hub namespace resource type? Are you monitoring the same metrics for all event hub namespaces? What do you see in the log for this message string: "QUERYING for metric definitions for type"

**Comment by RalfWenzel** [comment]
As i said 3 messages above 
- i removed tags from all EventHubs but one from to exlude this as a problem -> same problem with one EH
- I also removed all metric names except one from the one EH left. I'm using alternatively INREQS or SUCCREQ metric to trigger the 10 minutes sequence (Change tag to Metrics:INREQS, Then to SUCCREQ, then INREQS again, and so on)
- content:
"Microsoft.EventHub/namespaces":{  
       "metrics":[  
           "SuccessfulRequests",
           "ServerErrors",
           "UserErrors",
           "QuotaExceededErrors",
           "ThrottledRequests",
           "IncomingRequests",
           "IncomingMessages",
           "OutgoingMessages",
           "IncomingBytes",
           "OutgoingBytes",
           "ActiveConnections",
           "ConnectionsOpened",
           "ConnectionsClosed",
           "CaptureBacklog",
           "CapturedMessages",
           "CapturedBytes",
           "Size",
           "INREQS",
           "SUCCREQ",
           "FAILREQ",
           "SVRBSY",
           "INTERR",
           "MISCERR",
           "INMSGS",
           "EHINMSGS",
           "OUTMSGS",
           "EHOUTMSGS",
           "EHINMBS",
           "EHINBYTES",
           "EHOUTMBS",
           "EHOUTBYTES",
           "EHABL",
           "EHAMSGS",
           "EHAMBS"
       ]
