### ISSUE TITLE
Disambiguous Error Message: Wrong Value in KeyVault

### ISSUE THREAD

**Issue by tiny-dancer** [Microsoft/AzureMonitorAddonForSplunk#43]
This is an enhancement request.  Our plugin was not working and we determined root cause was the wrong value within Key Vault.  The only log message showing the issue was a `DEBUG` log statement wrapping an exception.  

Enhancement request to properly display the below exception as an `ERROR` statement

`
06-18-2018 20:37:13.907 +0000 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://test1==> RX ERROR on hub: insights-operational-logs, err: AmqpProtocolError: amqp:unauthorized-access:Attempted to perform an unauthorized operation. TrackingId:46ea9189251842499fc41ecf958c039a_G17, SystemTracker:gateway5, Timestamp:6/18/2018 8:37:13 PM
`

**Comment by ehershey** [comment]
adding real link to https://github.com/microsoft/AzureMonitorAddonForSplunk/pull/44 to this issue for easier navigating
