### ISSUE TITLE
Connecting to Splunk on-prem problems

### ISSUE THREAD

**Issue by manderso7** [microsoft/AzureMonitorAddonForSplunk#47]
We have accurate credentials in our input, as well as what we think is the correct Azure settings setup. I've setup an input for the Azure Monitor Activity Log, and am not getting any events into Splunk. We are seeing events in the EventHub related to Azure Monitor Activity. We're also not seeing any errors in the Splunk internal logs, even with debug turned on for ExecProcessor.  
By the way, we're not behind a proxy per issue 33, though we are on prem.
Any help would be appreciated. 

These are the events we're seeing in the internal Splunk log:

> 
> 06-25-2018 17:15:28.926 -0400 DEBUG ExecProcessor - cmd='/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh' Not added to run queue
> --
>   | 06-25-2018 17:15:28.926 -0400 DEBUG ExecProcessor - PipelineSet 1: Destroying ExecedCommandPipe for "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" id=6218
>   | 06-25-2018 17:15:28.926 -0400 DEBUG ExecProcessor - PipelineSet 1: Ran script: /opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh, took 6.460801 seconds to run, 0 bytes read 0 events read
>   | 06-25-2018 17:15:28.916 -0400 DEBUG ExecProcessor - PipelineSet 1: Got EOF from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh", uniqueId=6218
>   | 06-25-2018 17:15:28.906 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://aflazauditlog Five seconds of silence on all hubs, disconnecting.
>   | 06-25-2018 17:15:23.906 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://aflazauditlog Time is now: 2018-06-25T21:15:23.906Z
>   | 06-25-2018 17:15:23.895 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://aflazauditlog Checkpoint file name is: /opt/splunk/var/lib/splunk/modinputs/azure_activity_log/aflazauditlog_checkpoints.json
>   | 06-25-2018 17:15:23.894 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://aflazauditlog Checkpoint file name is: /opt/splunk/var/lib/splunk/modinputs/azure_activity_log/aflazauditlog_checkpoints.json
>   | 06-25-2018 17:15:23.894 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://aflazauditlog Checkpoint file name is: /opt/splunk/var/lib/splunk/modinputs/azure_activity_log/aflazauditlog_checkpoints.json
>   | 06-25-2018 17:15:23.238 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://aflazauditlog single input = {"SPNApplicationId":"keyid","SPNApplicationKey":"key","SPNTenantID":"superlongstring","disabled":"0","eventHubNamespace":"name","host":"psnsplunk09u","index":"main","interval":"60","secretName":"SplunkApplication","secretVersion":"secretversion","sourcetype":"amal:activityLog","vaultName":"vaultname"}
>   | 06-25-2018 17:15:23.238 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://aflazauditlog Streaming events from Azure Event Hubs until silence for 5 seconds.
> 06-25-2018 17:15:23.238 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://aflazauditlog single input = {"SPNApplicationId":"ID_NUM","SPNApplicationKey":"APPKEY","SPNTenantID":"TENID","disabled":"0","eventHubNamespace":"Dev-Az-Events","host":"psnsplunk09u","index":"main","interval":"60","secretName":"SplunkApplication","secretVersion":"SECVER","sourcetype":"amal:activityLog","vaultName":"KEYVAULT_name"}
> 06-25-2018 17:15:23.237 -0400 DEBUG ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://aflazauditlog password object: {"name":":AzureMonitorActivityLogAppKey:","service":{"scheme":"https","host":"localhost","port":8089,"username":null,"password":null,"sessionKey":"SessionKey","authorization":"Splunk","paths":{"apps":"/services/apps/local","capabilities":"authorization/capabilities","configurations":"configs","dataModels":"datamodel/model","deploymentClient":"deployment/client","deploymentServers":"deployment/server","deploymentServerClasses":"deployment/serverclass","deploymentTenants":"deployment/tenants","eventTypes":"saved/eventtypes","firedAlerts":"alerts/fired_alerts","indexes":"data/indexes","info":"/services/server/info","inputs":null,"jobs":"search/jobs","licenseGroups":"licenser/groups","licenseMessages":"licenser/messages","licensePools":"licenser/pools","licenseSlaves":"licenser/slaves","licenseStacks":"licenser/stacks","licenses":"licenser/licenses","loggers":"server/logger","login":"/services/auth/login","messages":"messages","passwords":"admin/passwords","parser":"search/parser","pivot":"datamodel/pivot","properties":"properties","roles":"authorization/roles","savedSearches":"saved/searches","settings":"server/settings","storagePasswords":"storage/passwords","users":"/services/authentication/users","typeahead":"search/typeahead","views":"data/ui/views","currentUser":"/services/authentication/current-context","submitEvent":"/services/receivers/simple"},"version":"default","timeout":0,"autologin":true,"http":{"version":"default","_cookieStore":{}},"prefix":"https://localhost:8089"},"qualifiedPath":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A","namespace":{"owner":"splunk-system-user","app":"TA-Azure_Monitor","sharing":"app"},"_properties":{"clear_password":"cleared_pass","eai:acl":null,"encr_password":"enc_pass","password":"********","realm":"","username":"AzureMonitorActivityLogAppKey"},"_state":{"name":":AzureMonitorActivityLogAppKey:","id":"https://localhost:8089/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A","updated":"1969-12-31T19:00:00-05:00","links":{"alternate":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A","list":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A","_reload":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A/_reload","edit":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A","remove":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A"},"author":"splunk-system-user","acl":{"app":"TA-Azure_Monitor","can_change_perms":true,"can_list":true,"can_share_app":true,"can_share_global":true,"can_share_user":true,"can_write":true,"modifiable":true,"owner":"splunk-system-user","perms":null,"removable":true,"sharing":"app"},"content":{"clear_password":"somanypasswords","eai:acl":null,"encr_password":"enc_pass","password":"********","realm":"","username":"AzureMonitorActivityLogAppKey"}},"_fields":{},"_acl":{"app":"TA-Azure_Monitor","can_change_perms":true,"can_list":true,"can_share_app":true,"can_share_global":true,"can_share_user":true,"can_write":true,"modifiable":true,"owner":"splunk-system-user","perms":null,"removable":true,"sharing":"app"},"_links":{"alternate":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A","list":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A","_reload":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A/_reload","edit":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A","remove":"/servicesNS/nobody/TA-Azure_Monitor/storage/passwords/%3AAzureMonitorActivityLogAppKey%3A"},"_author":"splunk-system-user","_updated":"1969-12-31T19:00:00-05:00","_published":null}

**Comment by sebastus** [comment]
try deleting the checkpoint file.

**Comment by manderso7** [comment]
Thanks, we'll try that and let you know.

**Comment by manderso7** [comment]
I never got the chance to try, we had another solution put into place while I was waiting on resources for this. I would try it though and reply if you can.
