### ISSUE TITLE
Question: Programmatically configure Monitor Addon in Splunk

### ISSUE THREAD

**Issue by tiny-dancer** [microsoft/AzureMonitorAddonForSplunk#49]
Currently our process requires a manual web UI step to configure the azure monitor addon in splunk forwarder, what is the recommendation to automating the plugin configuration? (.conf files, etc)

**Comment by sebastus** [comment]
most people use PowerShell scripts to enumerate their resources and create
the diagnostic profiles. The diagnostic profile is the object that you also
can create manually via the portal. I don't know of a way to script
settings up the configuration of the plugin in Splunk - perhaps your splunk
rep can help with that? There is a setup script in the repo that will
generate all of the configuration values for you.

**Comment by tiny-dancer** [comment]
thanks for the quick response

**Comment by bdschaap** [comment]
I'm interested in this as well.  The only approach I can think of to automate this is to install the app via Splunk CLI and configure the inputs.conf for the app.  Perhaps also using a Deployment Server to push the inputs.conf to the server.

**Comment by sebastus** [comment]
I haven't done any work on automating the installation. There is a script
referenced in the readme.md that helps with setting up a few of the
requirements and provides a list of the configuration settings for the data
inputs. feel like making a contribution?
