### ISSUE TITLE
Feature Request: New Azure Monitor Alert Category

### ISSUE THREAD

**Issue by abakiaydin** [microsoft/AzureMonitorAddonForSplunk#52]
Is it possible to add the 'alert' category published by Microsoft.SecurityGraph into the logCategories.json and the corresponding event hub into the hubs.json.

There is [this documentation ](https://developer.microsoft.com/en-us/graph/docs/concepts/security_siemintegration#step-3-download-and-install-the-azure-monitor-add-on-for-splunk-which-will-allow-splunk-to-consume-security-alerts) provided by Microsoft.SecurityGraph team to enable 'alert' logs. It would be great to have that category already configured in the add on.

Thanks

**Comment by sebastus** [comment]
Thanks for raising this to my attention. I read the documentation and found a couple of issues with it - and raised an issue with that documentation repo: https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/7763. Before I change the add-on I will nail down these questions with that documentation team. Thanks again. 

One last thing - are you seeing amal:security or amal:ascAlert sourcetypes in your Splunk index? These are coming from Activity Logs hub.

**Comment by abakiaydin** [comment]
I am not seeing amal:security or amal:ascAlert in my Splunk index. I am currently using trial version to test with the Azure Monitor add-on. 

Microsoft Security Graph is different than Azure Security Center, it is a new tenant level provider using diagnostic logs.
