### ISSUE TITLE
Add Resource Provider requirements to readme and/or script into PS or Bash script

### ISSUE THREAD

**Issue by stevenbukovic** [Microsoft/AzureMonitorAddonForSplunk#54]
Add Resource Provider requirements to readme and/or script into PS or Bash script

Getting errors about microsoft.insights when running through the "Azure configuration for Windows users" section.

**Comment by rickrain** [comment]
@stevenbukovic , do you recall which line in the script you were getting these errors?

**Comment by rickrain** [comment]
@stevenbukovic, disregard my previous question.  I just found it. Looks like when we're touching the log profile settings that it is going through the `microsoft.insights` provider.  I'm working on some doc updates now and will come back to this thread when finished.

**Comment by rickrain** [comment]
Documentation in README.MD has been updated.
