### ISSUE TITLE
Metrics Application Not Found in Directory

### ISSUE THREAD

**Issue by ConnorRules** [microsoft/AzureMonitorAddonForSplunk#55]
Currently have diagnostics and audit pulling data from Azure successfully. Using the same input settings for the metrics input gives the following error:
`ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_monitor_metrics.py" Error caught in get_metrics_for_subscription, type: <class 'adal.adal_error.AdalError'>, value: Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS70001: Application with identifier 'RootManageSharedAccessKey' was not found in the directory `

**Comment by sebastus** [comment]
The splunk configuration for metrics is different from that for the logs. Please take another look. Sounds like you put the value RootManageSharedAccessKey into the wrong field.

**Comment by ConnorRules** [comment]
Care to elaborate? The only difference I'm seeing in setting up the metrics input is adding the subscription ID and settings tags in azure. 

RootManageSharedAccessKey is only entered in the content type field alongside with the event hub namespace primary key into the vault.

**Comment by sebastus** [comment]
please send a screenshot of the config parameters for the metrics data input to me at golive@microsoft.com.
