### ISSUE TITLE
What is needed for the Secret

### ISSUE THREAD

**Issue by gbryniarski** [Microsoft/AzureMonitorAddonForSplunk#6]
I am confused regarding the secret - what is expected here?

Is is a SAS token?   A connection string?  Some other format?

Thanks

**Comment by sebastus** [comment]
Apologies for the delay getting back to you. There are two types of secrets depending on the data input. 

1. The log (activity & diagnostic) data inputs require an event hub access policy and the key for that policy.

2. The metrics data input requires the service principal name and password.

The Key Vault secret stores the access policy + key for a log data input and the service principal name and password for the metrics data input.
