### ISSUE TITLE
Set-AzureRmKeyVaultAccessPolicy Error in when running azure-setup.ps1

### ISSUE THREAD

**Issue by stevenbukovic** [microsoft/AzureMonitorAddonForSplunk#60]
I am currently working with a tenant/subscription sysadmin to set this up to send log data through event hub to Splunk.  I was able to work through this with out issue in a pay-as-you-go subscription but working on this in an enterprise agreement tenant we are running into trouble getting the azure-setup.ps1 script to complete successfully.  Can you review and possibly help identify what may be missing in the subscription/tenant that would be causing the script to not complete.  Below is the error we are getting:

_\azure-setup.ps1
Creating resource group 'SiemPipeRG' in region 'Central US'.
Creating event hub namespace 'spleh################' in resource group 'SiemPipeRG'.
Creating Key Vault 'splkv################' in resource group 'SiemPipeRG'.
- Setting default access policy for 'example@redacted.account.example'
Set-AzureRmKeyVaultAccessPolicy : Cannot find the Active Directory object '' in tenant
'REDACTED'. Please make sure that the user or application service principal you are
authorizing is registered in the current subscription's Azure Active directory. The TenantID displayed by the cmdlet
'Get-AzureRmContext' is the current subscription's Azure Active directory.
At C:\temp\azure-setup.ps1:33 char:1
+ Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName $keyVault.Resource ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmKeyVaultAccessPolicy], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy_

**Comment by stevenbukovic** [comment]
We are also wondering if the following article relays the reasoning behind why we are getting the error:

https://social.msdn.microsoft.com/Forums/azure/en-US/ae8d2782-ecf7-4d35-9859-d4455e65a668/setazurermkeyvaultaccesspolicy-cannot-find-the-active-directory-object-in-tenant-?forum=AzureKeyVault

**Comment by sebastus** [comment]
@rickrain would you mind taking a look at this?

**Comment by rickrain** [comment]
@stevenbukovic, is user interactive user (ie: the user running the script) in Azure AD?  It is a requirement that the user running the script be present in tenant/directory you're configuring for.

**Comment by stevenbukovic** [comment]
Yes it is

**Comment by rickrain** [comment]
Ok.  Then the next step would be to edit the script and place the `-Debug` switch on the end of the line where `Set-AzureRmKeyVaultAccessPolicy` is called.  This will generate some additional output that may provide details on why this is happening.

**Comment by aaslanyan2** [comment]
I am experiencing the same exact symptom. No issues executing the script using my personal pay-as-you-go subscription, but run into the error referenced above when executing in our work environment. An important detail that may help shed some light; the Azure subscription being used is federated with Office 365 tenant. My personal pay-as-you-go subscription does not have any federation; Azure AD is part of the existing subscription. Could the issue with the script boil down to using a given Azure subscription and having the Azure AD point to a federated tenant in Office 365?

Set-AzureRmKeyVaultAccessPolicy : Cannot find the Active Directory object '' in tenant '[REDACTED]'. Please make sure that the user or application service principal you are authorizing is registered in the current subscription's Azure Active
directory. The TenantID displayed by the cmdlet 'Get-AzureRmContext' is the current subscription's Azure Active directory.
At C:\Users\XXXXX\scripts\azure-setup.ps1:33 char:1
+ Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName $keyVault.Resource ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmKeyVaultAccessPolicy], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

**Comment by JosephCason** [comment]
My customer is receiving the same errors.  Rick and Greg, I may reach out to you direct on the debug output.  What is odd is it worked several months ago.

**Comment by Sergmis** [comment]
PutS et-AzKeyVaultAccessPolicy command and parameters all on one line with one space between -parameter and value.  This worked for me.  Copying examples copied over spaces that generated the "Cannot find the Active Directory object '' in tenant"

**Comment by sebastus** [comment]
Sergio, thanks for the response. It helps me a lot when others in the
community make a contribution. Cheers!

Greg

PS: In general the -AzureRMxxx cmdlets should be replaced with the newer
-Azxxx cmdlets.

**Comment by ishantshrestha** [comment]
.\azure-setup.ps1
Creating resource group '*******' in region 'South India'.
Creating event hub namespace 'spleh******************' in resource group 'Splunk'.
Creating Key Vault 'splkv***************' in resource group 'Splunk'.
- Setting default access policy for '***********@onmicrosoft.com'
Set-AzureRmKeyVaultAccessPolicy : Cannot find the Active Directory object '' in tenant
'*******-****-****-****-********'. Please make sure that the user or application service principal you are
authorizing is registered in the current subscription's Azure Active directory. The TenantID displayed by the cmdlet
'Get-AzureRmContext' is the current subscription's Azure Active directory.
At C:\Program Files\Splunk\etc\apps\AzureMonitorAddonForSplunk-master\scripts\azure-setup.ps1:33 char:1
+ Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName $keyVault.Resource ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmKeyVaultAccessPolicy], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

This is the issue I am facing....I am using the free trial version of Microsoft Azure.

**Comment by mythdevishere** [comment]
There's a small change you need to make in the script for the below command.
Instead of -emailaddress, you need to use -UserPrincipalName as shown below.

Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName $keyVault.ResourceGroupName -VaultName $keyVault.VaultName -UserPrincipalName $azureSession.Context.Account -PermissionsToSecrets get,list,set,delete,recover,backup,restore -PermissionsToKey get,list,update,create,import,delete,recover,backup,restore
