### ISSUE TITLE
Unable to initialize modular input "azure_monitor_metrics

### ISSUE THREAD

**Issue by tomomu** [microsoft/AzureMonitorAddonForSplunk#63]
I saw no fix to this:

Running Ubuntu 17.10. 
I get this error when running : npm install in /opt/splunk/etc/apps/TA-Azure_Monitor/bin/app:

npm WARN azure_monitor@1.2.0 No repository field.

And I get the famous error "Unable to initialize modular input "azure_monitor_metrics" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_monitor_metrics: script running failed (exited with code 1)." from Splunk.

**Comment by sebastus** [comment]
Metrics are python. Did you install the python dependencies?

**Comment by tomomu** [comment]
Yes I did. I followed every step. The only error I received was at the final npm install.

**Comment by sebastus** [comment]
Next step is to turn on debug logging for ExecProcessor.

**Comment by tomomu** [comment]
Coming back to this. I am running ./am_depends_ubuntu.sh and this still fails when executing:

 pip install msrestazure -t $SPLUNK_HOME/etc/apps/TA-Azure_Monitor/bin

....
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography>=1.1.0->adal<2.0.0,>=0.6.0->msrestazure)
jwt 0.5.2 has requirement cryptography==1.7.2, but you'll have cryptography 2.3.1 which is incompatible.
jwt 0.5.2 has requirement typing==3.5.3.0, but you'll have typing 3.6.6 which is incompatible.

**Comment by sebastus** [comment]
Hi - the installation script is synchronised with the latest version of the
add-on. If you're executing commands out of that context, you could have
conflicting packages. I would suggest removing and re-installing the add-on
v1.3.1. The newest am_depends files restrict dependencies to the add-on
folders so they don't impact the system at large.

**Comment by tomomu** [comment]
Thank you. I stumbled on this solution last night - and setting $splunk_home. Now working.
