### ISSUE TITLE
Data is not forwarded from Azure to Splunk even after connection works fine

### ISSUE THREAD

**Issue by gaurav7961** [Microsoft/AzureMonitorAddonForSplunk#66]
We are trying to forward Activity logs from Azure into Splunk.
We have setup both systems as per https://www.splunk.com/blog/2018/04/20/splunking-microsoft-azure-monitor-data-part-1-azure-setup.html and https://www.splunk.com/blog/2018/05/07/splunking-microsoft-azure-monitor-data-part-2-splunk-setup.html

There are no errors in connecting to Azure from Splunk but data is not forwarded. Also there are no logs so it's kind of mysterious that data is lost somewhere.
In Azure, we can see data in Event hub and also we can see that data can be forwarded (we tested by creating a function app as a consumer of event hub)

**Comment by sebastus** [comment]
@gaurav7961 please contact me at golive@microsoft.com so we can figure out what's going on.

**Comment by sebastus** [comment]
@gaurav7961 I worked with another customer on this and discovered they had a firewall preventing the add-on from communicating with the internet. It somehow prevented the connection attempt from timing out, so nothing appeared in the log. I'm working on improving messaging in this scenario. Are you in a position to test it?

**Comment by gaurav7961** [comment]
Hi Greg,

Thank you for your response. But now we are using function App instead of addon.

Best,
Gaurav
