### ISSUE TITLE
TA-Azure_Monitor fails with AmqpProtocolError: amqp:unauthorized-access

### ISSUE THREAD

**Issue by dennymj** [Microsoft/AzureMonitorAddonForSplunk#67]
TA-Azure_Monitor fails with AmqpProtocolError: amqp:unauthorized-access
08-17-2018 12:45:44.663 -0700 DEBUG ExecProcessor - message from "/opt/splunk/7.1.2/multirole/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" Modular input azure_diagnostic_logs://Azure ==> RX ERROR on hub: szwus2-ehn-00001_01, err: AmqpProtocolError: amqp:unauthorized-access:An AMQP error occurred (condition='amqp:unauthorized-access'). TrackingId:6476670152ec49f29c32c94f251c045d_G23, SystemTracker:gateway5, Timestamp:8/17/2018 7:45:44 PM

08-17-2018 14:36:33.392 -0700 DEBUG ExecProcessor - message from "/opt/splunk/7.1.2/multirole/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" Modular input azure_diagnostic_logs://Azure ==> RX ERROR on hub: szwus2-ehn-00001_01, err: AmqpProtocolError: com.microsoft:argument-out-of-range:The specified partition is invalid for an EventHub partition sender or receiver. It should be between 0 and 1.

We've verified Event hub and networking with test app running from private network, sample app pulls message as expected. No firewalls blocking amqp request.
https://github.com/Azure/azure-event-hubs/blob/master/samples/DotNet/Microsoft.Azure.EventHubs/SampleEphReceiver/readme.md 

We've duplicated this on RHEL 7.2 and Windows 2012 server R2

**Comment by sebastus** [comment]
@dennymj all hubs should be set up with 4 partitions, no more, no less.

**Comment by dennymj** [comment]
amqp:unauthorized-access caused by Client connection for amqps request SAS name is undefined, the creds.sasKeyName is not returning as expected.
https://github.com/Microsoft/AzureMonitorAddonForSplunk/blob/master/bin/app/azure_monitor_logs.js#L617
Logger.debug(name, String.format('Event Hub URI is : {0}', uri));

08-21-2018 10:49:40.709 -0700 DEBUG ExecProcessor - message from "/opt/splunk/7.1.2/multirole/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" Modular input azure_diagnostic_logs://Azure Event Hub URI is : amqps://**undefined**:Oi7%2BCRETV4PTgz%2BlEscZ7PAj7XXXXXXXXX@SZWUS2-EHN-00001.servicebus.windows.net

**Comment by dennymj** [comment]
environment Public Azure,seems environment keyvaultResource is incorrect
 var resource = environments[environment].keyvaultResource;
 "keyvaultResource": "https://vault.azure.net",

example key vault DNS name https://szwus2-001.vault.azure.net/

**Comment by sebastus** [comment]
More likely is your service principal doesn't have the rights to read key
vault.

**Comment by dennymj** [comment]
We validated this with Azure support, SP granted reader, this is the doc we've verified steps complete.
 
https://developer.microsoft.com/en-us/graph/docs/concepts/security_siemintegration#step-4-register-an-application-with-your-tenant-azure-active-directory-which-splunk-will-use-to-read-from-the-event-hub

**Comment by sebastus** [comment]
Going back to the error message with amqps://undefined...

The line of code that generates that URL is:
var uri = 'amqps://' + encodeURIComponent(creds.sasKeyName) + ':' + encodeURIComponent(creds.sasKeyValue) + '@' + serviceBusHost;

creds.sasKeyName comes from subs.getEventHubCreds, which gets those creds from key vault.

Since sasKeyName is coming back as undefined, I guess that they aren't being returned from the key vault, and so I again guess that the creds to key vault aren't right or the service principal doesn't have the correct rights.

Let me know what you discover as you investigate these things.

You can test the creds and rights by using the Azure CLI v2 (az). You can sign into the tool using the service principal creds and then attempt to access the secret in the key vault.

**Comment by dennymj** [comment]
Azure CLI with SP shows keyvault secrect as expected. The Splunk TA has the same creds.
az login --service-principal --username
az keyvault secret show --name szw

  "contentType": null,
  "id": "https://szwXXXXXXX-001.vault.azure.net/secrets/szXXXXXkey-001/dadcaXXXXXXXXXXXXXXXXX",
  "kid": null,
  "managed": null,
  "tags": null,
  "value": "Oi7+CXXXXXXXXXXXX"
  
‘undefined’ is for SASKeyName, set from value of response.contentType
https://github.com/Microsoft/AzureMonitorAddonForSplunk/blob/master/bin/app/subs.js#L73
I tried adding Logger.debug to capture response.contentType value but the following is not working
var Logger = ModularInputs.Logger; 

var creds = { sasKeyName: response.contentType, sasKeyValue: response.value }; 
Logger.debug(name, String.format('key vault creds : {0}', creds));

**Comment by dennymj** [comment]
After Key vault secret, content type (optional) set to RootManageSharedAccessKey, TA Azure monitor is pulling Eventhub messages successfully.
