### ISSUE TITLE
Activity Logs captured but not Diagnostics and Metrics in Splunk

### ISSUE THREAD

**Issue by abhiravi7** [microsoft/AzureMonitorAddonForSplunk#68]
Hi all,
I was able to configure this app fairly quickly and get the modular data inputs working. 
I created an input for Activity, Diagnostic and Metric log collection.
However, I am seeing data collected from eventhub for only activity logs, NOT diagnostic and Metrics.
In the internal logs I see no errors for diagnostic and metrics (.sh scripts are executing). 

I would appreciate any help from the community in troubleshooting/debugging why diagnostics and metric logs are not captured. 

EDIT: We are also writing eventhub data for the 3 categories to a storage account and we are seeing all the data reside in the storage container. 

Thank you!

**Comment by sebastus** [comment]
@abhiravi7 

re: diagnostic logs. what resources did you configure to output diagnostic logs? what hubs are the logs going to? are the hubs in hubs.json in bin/app folder?

re: metrics. did you tag any resources? the tag is case sensitive: Metrics. Easiest tag is Metrics: *. (without the period)

**Comment by sebastus** [comment]
What resources did you tag? What tags did you add?

There is no json file to configure metrics tags.

**Comment by abhiravi7** [comment]
Hi Greg,

Thank you for your response and patience.
I am trying to resolve this issue as soon as possible. 
The following tag was added to turn on the metrics listed within tag:    Metrics : CPU Time,Requests,Average Response Time,Connections
I still do not see any event count for azure_metric_log.
I appreciate any further details on this.

**Comment by abhiravi7** [comment]
Hi Greg,
I am seeing the following message under metrics collection. Can you explain why this message appears?

ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_monitor_metrics.py" Error caught in get_metrics_for_subscription, type: <class 'requests.exceptions.ConnectionError'>, value: HTTPSConnectionPool(host='kv****.vault.azure.net', port=443): Max retries exceeded with url: /secrets/myRESTAPICredentials/4ae81b1f183b4eae8bf7e845ac86119b?api-version=2016-10-01 (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer), locale = get_secret_from_keyvault

**Comment by abhiravi7** [comment]
Also a quick question. If I see events that have average, min, max and metricName. Does that signify Metrics data? Only reason I ask is because in sourcetype I see activity and diagnostic but see data that sounds like metric data. (Refer screenshot)
![image](https://user-images.githubusercontent.com/42576909/46824401-ba3d4e80-cd5e-11e8-9009-f2dd231b5764.png)
