### ISSUE TITLE
Self Signed certificate in certificate chain

### ISSUE THREAD

**Issue by eskarthi** [microsoft/AzureMonitorAddonForSplunk#70]
Hello,

I have followed the steps in github and setup everything correctly, however i still get self signed certificate error.

ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure Activity Log Moni
tor Error getting event hub creds: Error: self signed certificate in certificate chain

In addition to that i have added servicebus,microsoft certificates in cacerts and restarted splunk server. Still no luck

Your help will be greatly appreciated.

Thanks in advance.
Karthik

**Comment by droodleskins** [comment]
eskarthi - I'm not sure if this is the case here - but we use Azure PaaS - and we could not connect to the splunk HEC using the Splunk signed cert OR even with a Company signed cert. We had to obtain a public signed cert from symantec\digicert and only then did the connection work over https to the HEC

**Comment by eskarthi** [comment]
Thank you , will try with public signed cert and let you know .

**Comment by jonwalthour** [comment]
I am receiving the same error. I have tried using a publicly signed cert, but it has not resolved the issue. Any help would be very much appreciated.

message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure Monitor Activity Log Error getting event hub creds: RequestError: Error: self signed certificate in certificate chain
