### ISSUE TITLE
Azure Monitor metrics with dimensions or filters

### ISSUE THREAD

**Issue by sebastiankasprzak** [Microsoft/AzureMonitorAddonForSplunk#74]
I have tried setting up collection for some additional metrics, i.e. https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics#microsoftcontainerservicemanagedclusters

The issue I'm seeing is that the metrics that have defined dimensions are not collected properly, the dimension or filter information does not appear alongside the json payload in splunk and therefore those metrics are useless on their own.

Am I right in thinking that within current implementation of Azure Metrics script the concept of dimensions and filters is not supported or am I missing something?

**Comment by sebastus** [comment]
@sebastiankasprzak would you contact me for this on golive@microsoft.com?
