### ISSUE TITLE
Values not consistently returned

### ISSUE THREAD

**Issue by kendo214** [microsoft/AzureMonitorAddonForSplunk#76]
We are successfully collecting diagnostic logs, activity logs, and to an extent metric logs.  We are on Splunk Enterprise 7.1.2, Redhat Linux, and 1.2.9 of the addon.  As an example, we're collecting 'Disk Read Bytes' on our VM resources (verified tagging, we can see it in the json viewer, wget of the Azure API returns a value) and we will see events like the one below.  Note that the only data is a timeStamp, there is no 'Value' for the Disk Read Bytes.  This isn't an issue just for this metric, we see it across the board.  Any ideas?

  	 amm_resourceGroup:	 BLAH01-RG	
  	 amm_resourceName:	 BLAH01-BLAH1	
  	 amm_resourceType:	 MICROSOFT.COMPUTE/VIRTUALMACHINES	
  	 amm_subscription_id:	 oursubid
  	 data:	{	[-]	
    	 timeStamp:	 2018-09-19T14:18:00Z	
  	}	
  	 id:	 /subscriptions/oursubid/resourceGroups/BLAH01-RG/providers/Microsoft.Compute/virtualMachines/BLAH01-blah1/providers/Microsoft.Insights/metrics/Disk Read Bytes	
  	 name:	{	[-]	
    	 localizedValue:	 Disk Read Bytes	
    	 value:	 Disk Read Bytes	
  	}	
  	 type:	 Microsoft.Insights/metrics	
  	 unit:	 Bytes

**Comment by sebastus** [comment]
This has to do with the way metrics are generated and returned from the platform. See the Sample Response on this page: https://docs.microsoft.com/en-gb/rest/api/monitor/metrics/list, note that in some time blocks, no metric is returned. The queries submitted by the add-on are time boxed in the same way. There's a checkpoint file for the metric, so the time box = Now() - LastTime().
