### ISSUE TITLE
Error getting metrics

### ISSUE THREAD

**Issue by TheFausap** [Microsoft/AzureMonitorAddonForSplunk#79]
Hello,

I have the following error in my splunkd.log when I try to get metric logs (I'm using the TA 1.30)

`ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_monitor_metrics.py" Error caught in get_metrics_for_subscription, type: <type 'exceptions.TypeError'>, value: string indices must be integers, locale = get_resources_for_rgs`

thanks,
Fausto

**Comment by sebastus** [comment]
Similar to this one:
https://github.com/Microsoft/AzureMonitorAddonForSplunk/issues/75

**Comment by TheFausap** [comment]
Yeah, it was really a permission problem in Azure Directory App, accessing the Subscription as Reader.

Thanks.
