### ISSUE TITLE
Unable to pull messages from Event hubspace due to "AmqpProtocolError: amqp:unauthorized-access"

### ISSUE THREAD

**Issue by Anusha20** [microsoft/AzureMonitorAddonForSplunk#80]
Hi 
Getting the following exception on trying to read data from eventhubspace.

ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_diagnostic_logs.sh" Modular input azure_diagnostic_logs://azure_keyvault_test ==> RX ERROR on hub: insights-logs-auditevent, err: AmqpProtocolError: amqp:unauthorized-access:An AMQP error occurred (condition='amqp:unauthorized-access'). TrackingId:28d35d664a764a00a8916e639f56388e_G20, SystemTracker:gateway5, Timestamp:9/26/2018 2:49:53 PM

Any help is much appreciated.

Regards
Anusha

**Comment by sebastus** [comment]
Might the service principal not have sufficient rights?

**Comment by sebastus** [comment]
Another customer had this problem recently. The solution is: ensure that the event hub credential secret in key vault has the name of the event hub security policy in the Content Type. This is for most people "RootManageSharedAccessKey"
