### ISSUE TITLE
No module named splunklib.client

### ISSUE THREAD

**Issue by Benthewater** [Microsoft/AzureMonitorAddonForSplunk#83]
Hi,

Currently I am installing this add-on on the Splunk HF RHEL 7 server and have followed the installation steps.

However, the Azure Activity logs are not coming into Splunk and there is an error in the internal logs:
ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" ImportError: No module named splunklib.client

Anyone else having this issue as well?

**Comment by sebastus** [comment]
You followed the instructions on this page? https://github.com/Microsoft/AzureMonitorAddonForSplunk/wiki/Installation-on-Linux

splunklib is one of the required dependencies. Both python and node.js variants are required.

**Comment by Benthewater** [comment]
Thanks for the swift response!

Yes I did. I followed exactly as per instructed and I can see splunklib in the bin directory within the add-on. The error will be generated the moment I enable the inputs for Activity logs and no log is coming in.

**Comment by sebastus** [comment]
do you also see splunklib in the app/node_modules directory? if not, did
you run "npm install"?

**Comment by Benthewater** [comment]
I did and no there's no splunklib in the node_modules directory. Only splunk-sdk. How do I manually install that component in this directory?

**Comment by Benthewater** [comment]
Okay I will give it a try. On another note, does the Activity Logs include Security Logs such as Risky Sign Ins?

**Comment by Benthewater** [comment]
I encountered this error when I enabled the data inputs for Azure Activity Logs:

Modular input azure_activity_log://Azure Activity Log No connection on hub: insights-operational-logs. Is there a network route to the endpoint?

Is this the reason why the data isnt coming in?
