### ISSUE TITLE
amal:activityLog sourcetype not found

### ISSUE THREAD

**Issue by kendo214** [microsoft/AzureMonitorAddonForSplunk#84]
I'm not seeing this sourcetype coming in, although diagnostic logs are coming in with various categories including 'AuditEvent'.

Both Diagnostic Logs and Activity Log inputs are pointed to the same event hub, keyvault, etc.  Do these need to be separated out in order for this to work?

**Comment by sebastus** [comment]
that's a default sourceType, in case the operation name in the message isn't recognized. check this routine for other source types that you should expect to see. 

https://github.com/Microsoft/AzureMonitorAddonForSplunk/blob/428ccbef6e0cf6146b54290ec92a4bc2b930b289/bin/app/azure_monitor_logs.js#L268
