### ISSUE TITLE
No logs coming in even though EventHubs show activities

### ISSUE THREAD

**Issue by Benthewater** [microsoft/AzureMonitorAddonForSplunk#91]
Any ideas how I can troubleshoot this? I have managed to resolve all the previous issue with this add-on but there's no data coming in.

I am trying to collect Azure Activity logs.

**Comment by mpras123** [comment]
it's little for me, just one event came through, and nothing after that.

**Comment by mpras123** [comment]
Thank you for your response, you are right the activity logs aren't voluminous, i have configured AAD audit to stream to Events hub and now i am seeing those logs coming in.

**Comment by Benthewater** [comment]
Hi mpras123, can you share the configuration steps which you use to configure AAD audit to stream to Events hub? I am still not seeing any logs coming in unfortunately..

This morning I check my Splunk and it has more errors.. The following are the sample error logs:

1) No connection on hub: insights-operational-logs. Is there a network route to the endpoint?
2) Error getting event hub creds: RequestError: Error: getaddrinfo ENOTFOUND

**Comment by sebastus** [comment]
@Benthewater I added the message you reference (1) specifically to catch those situations where there is no network path from the Splunk box to the various required Azure services, such as Key Vault and Event Hubs. Look to your firewall & routing rules if you're on prem. Look at your NSG filters if Splunk is in Azure.
