### ISSUE TITLE
Missing metrics that are displaying in azure

### ISSUE THREAD

**Issue by thematos** [Microsoft/AzureMonitorAddonForSplunk#92]
I am having issues getting the app to pull consistent numbers. I have a few gaps with the data.total field, but data.average has many gaps and it does not seem to be pulling in data.max and data.min. I went to the metrics section in azure and pulled down an excell looking at cpu time for an app service, then ran the search in splunk for data.average=*. I attached a screenshot of the timeline, example event from splunk. and what the same data looked like from the excell taken from azure.

{	[-]	
  	 amm_resourceGroup:	 XXX	
  	 amm_resourceName:	 XXX	
  	 amm_resourceType:	 MICROSOFT.WEB/SITES	
  	 amm_subscription_id:	XXX	
  	 data:	{	[-]	
    	 average:	 830.3529411764706	
    	 timeStamp:	 2018-10-24T15:13:00Z	
  	}	
  	 id:	 XXX/providers/Microsoft.Insights/metrics/CpuTime	
  	 name:	{	[-]	
    	 localizedValue:	 CPU Time	
    	 value:	 CpuTime	
  	}	
  	 type:	 Microsoft.Insights/metrics	
  	 unit:	 Seconds	
}

![2018-10-24 10_29_15-search _ splunk 7 1 2](https://user-images.githubusercontent.com/44415117/47442973-00d87300-d779-11e8-93c9-dbba1933c263.png)

10/24/2018 10:09 | 934.388889
-- | --
10/24/2018 10:10 | 716.5
10/24/2018 10:11 | 1023.88889
10/24/2018 10:12 | 952.611111
10/24/2018 10:13 | 830.352941
10/24/2018 10:14 | 1023.36842
10/24/2018 10:15 | 901.5
10/24/2018 10:16 | 785.166667
10/24/2018 10:17 | 859.764706
10/24/2018 10:18 | 640.277778
10/24/2018 10:19 | 687.947368
10/24/2018 10:20 | 864.944444
10/24/2018 10:21 | 669.666667

**Comment by sebastus** [comment]
If you use a REST tool like Postman you'll see the same results. The add-on doesn't interpret or alter the numbers it gets from Azure in any way. The queries sent to Azure have a time bracket. If there is no metric reported in that time frame, you won't see a number in your splunk query.
