### ISSUE TITLE
Receiving logs sometimes duplicates sometime missing

### ISSUE THREAD

**Issue by riotkris** [microsoft/AzureMonitorAddonForSplunk#93]
Hi,

We are receiving 5000 sign in and 500 audit logs per day successfully however there is a small amount of either missing logs, duplicate logs and in some cases triplicate audit logs.

Have validated this by manually exporting the logs out of the event hub and comparing.

We also receive the below error at each polling interval. Could this be related to the issue?

11-07-2018 12:24:17.872 +1000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://azure-input ==> RX ERROR on hub: insights-operational-logs, err: AmqpProtocolError: com.microsoft:argument-out-of-range:The specified partition is invalid for an EventHub partition sender or receiver. It should be between 0 and 1.

**Comment by sebastus** [comment]
re: the error in the logs. This means you have a hub with the wrong number of partitions. It should have 4 partitions exactly. You'll have to delete and recreate it. Any diagnostic profiles associated with it will need to be recreated.

re: duplicates and missing messages. This is the first evidence of such events. Let's clear up the error above first, then see if the situation persists.

**Comment by riotkris** [comment]
Thanks Greg, we have created with 4 partitions and don't receive the error anymore.

Is it possible to change the target event hub name? Previously we tried changing the name however receive the below message if we don't use the default. Also tried using {Namespace}/{Event hub name} for the "eventHubNamespace" parameter without any luck.

"Modular input azure_activity_log://azure-input ==> Did not find hub: insights-operational-logs"

**Comment by sebastus** [comment]
Activity logs expect that name. Diagnostic logs can be configured to use
any name for the hub.

**Comment by RichieB2B** [comment]
Where does the requirement to have exactly 4 partitions in the EventHub come from?

It seems the number 4 is simply [hard coded](https://github.com/microsoft/AzureMonitorAddonForSplunk/blob/7e318d02e0b3d0a3aea7f5a3914ac46dc5ba35f0/bin/app/azure_monitor_logs.js#L641) by while it easily could have been made configurable IMHO.
