### ISSUE TITLE
Unable to pull Azure Activity Log

### ISSUE THREAD

**Issue by skhanewb** [microsoft/AzureMonitorAddonForSplunk#94]
Please see following errors once data inputs are configured on a heavy forwarder:

11-02-2018 04:52:30.541 -0700 ERROR ExecProcessor - message from ""C:\Program Files\Splunk\etc\apps\AzureMonitorAddonForSplunk-master\bin\azure_activity_log.cmd"" [SPLUNKD] Application does not exist: TA-Azure_Monitor
11-02-2018 04:52:30.541 -0700 ERROR ExecProcessor - message from ""C:\Program Files\Splunk\etc\apps\AzureMonitorAddonForSplunk-master\bin\azure_activity_log.cmd"" Modular input azure_activity_log://Azure_Activity Error 404 in the password waterfall: {1}
11-02-2018 04:52:30.541 -0700 ERROR ExecProcessor - message from ""C:\Program Files\Splunk\etc\apps\AzureMonitorAddonForSplunk-master\bin\azure_activity_log.cmd"" Modular input azure_activity_log://Azure_Activity Error creating storage passwords: {"response":{"headers":{"date":"Fri, 02 Nov 2018 11:52:30 GMT","cache-control":"private","content-type":"application/json; charset=UTF-8","x-content-type-options":"nosniff","content-length":"85","vary":"Authorization","connection":"Close","x-frame-options":"SAMEORIGIN","server":"Splunkd"},"statusCode":404},"status":404,"data":{"messages":[{"type":"ERROR","text":"Application does not exist: TA-Azure_Monitor"}]},"error":null}
11-02-2018 04:52:30.541 -0700 ERROR ExecProcessor - message from ""C:\Program Files\Splunk\etc\apps\AzureMonitorAddonForSplunk-master\bin\azure_activity_log.cmd"" Modular input azure_activity_log://Azure_Activity Error getting secrets from storagePasswords: {"response":{"headers":{"date":"Fri, 02 Nov 2018 11:52:30 GMT","cache-control":"private","content-type":"application/json; charset=UTF-8","x-content-type-options":"nosniff","content-length":"85","vary":"Authorization","connection":"Close","x-frame-options":"SAMEORIGIN","server":"Splunkd"},"statusCode":404},"status":404,"data":{"messages":[{"type":"ERROR","text":"Application does not exist: TA-Azure_Monitor"}]},"error":null}
11-02-2018 04:52:30.541 -0700 ERROR ExecProcessor - message from ""C:\Program Files\Splunk\etc\apps\AzureMonitorAddonForSplunk-master\bin\azure_activity_log.cmd"" [SPLUNKD] Application does not exist: TA-Azure_Monitor
11-02-2018 04:52:30.541 -0700 ERROR ExecProcessor - message from ""C:\Program Files\Splunk\etc\apps\AzureMonitorAddonForSplunk-master\bin\azure_activity_log.cmd"" Modular input azure_activity_log://Azure_Activity Error 404 in the password waterfall: {1}

**Comment by sebastus** [comment]
Is Splunk on prem? Can the Splunk box see the internet / Azure?

**Comment by sebastus** [comment]
for the activity log data input, can you email a screenshot of the splunk settings? golive@microsoft.com. Feel free to obscure any private values.

**Comment by santosh4071** [comment]
what is the update , i am also facing the same issue

**Comment by sebastus** [comment]
No update so far. Can you email your splunk settings as noted above?

**Comment by acstyche** [comment]
Hello,
We are seeing the same errors for azure_activity_log.cmd and azure_diagnostic_logs. cmd. Was the cause ever discovered?
