### ISSUE TITLE
Client forbidden & Access Denied

### ISSUE THREAD

**Issue by droodleskins** [microsoft/AzureMonitorAddonForSplunk#95]
I have tried to configure both metrics and activity log and getting these errors - having followed all the steps (so i thought) where am i likely to have gone wrong ?

ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_monitor_metrics.py" Error caught in get_metrics_for_subscription, type: <class 'requests.exceptions.HTTPError'>, value: 403 Client Error: Forbidden for url: https://host-keyvault.vault.azure.net/secrets/host-metrics-secret/XXXXXXXXXXXXX91ae369b3158ccf6?api-version=2016-10-01, locale = get_secret_from_keyvault

&

ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://host-AL Error getting event hub creds: StatusCodeError: 403 - {"error":{"code":"Forbidden","message":"Access denied","innererror":{"code":"AccessDenied"}}}

**Comment by sebastus** [comment]
It appears that the security entity (SPN or MSI) doesn't have rights to read secrets in key vault. In the wiki, there's a reference to a web page describing how to set the correct permissions for the SPN.

**Comment by droodleskins** [comment]
i am admin in the subscription.

just added the app to the keyvault policy and gave it all permissions - now see this 👍 

ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_monitor_metrics.py" Error caught in get_metrics_for_subscription, type: <class 'adal.adal_error.AdalError'>, value: Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'RootManageSharedAccessKey' was not found in the directory '3f23XXXXXXXXXXXXXXXX3346c70b02a'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant\r\nTrace ID: 9cf69c37-08f2XXXXXXXXXXc2900\r\nCorrelation ID: 4cf63993-bb03-4b98-8788-58d13b499a23\r\nTimestamp: 2018-11-08 12:54:06Z","error_codes":[700016],"timestamp":"2018-11-08 12:54:06Z","trace_id":"9cf69c37-08f2-4de5-85e1-5fe6737c2900","correlation_id":"4cf63993-bb03-4b98-8788-58d13b499a23"}, locale = get_access_token

**Comment by sebastus** [comment]
Splunk config is wrong. The log config and metrics config are different.

**Comment by droodleskins** [comment]
yep i have different configs for both .. the metrics also have the subscription ID
i cannot see where the splunk config is wrong - how do i find out ?

**Comment by sebastus** [comment]
The message says that when trying to get metrics for subscription, "
Application with identifier 'RootManageSharedAccessKey' was not found in
the directory..." RootManageSharedAccessKey has to do with Event Hubs.
Metrics doesn't use event hubs at all. So if your metrics config says
anything about RootManageSharedAccessKey, it's wrong.

**Comment by droodleskins** [comment]
I've spent a long time trying to get this work now ..

currently i'm seeing this \:
Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'RESTApplicationSecret' was not found in the directory '3f2313f8-fa99-4f68-a608-03346c70b02a'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant

I don't really follow -

Key Vault
For each credential that will be stored in Key Vault, create a secret. The name of the secret is your choice. Make the content type of the secret the name of the credential. Make the value of the secret the key of the credential. So:

REST API credentials, application id -> secret content type.
REST API credentials, application key -> secret value.
Event Hub credentials, SAS policy name -> secret content type.
Event Hub credentials, SAS policy key -> secret value.

**Comment by sebastus** [comment]
For the Metrics data input, store REST API credentials in the key vault
secret.

For the Logs data inputs (both activity and diagnostic), store Event Hub
credentials in the key vault secret.

From the message text, it appears that you're working with the metrics data
input and that the values stored in the key vault secret are not an Azure
AD service principal (spn) app id & key. You should put the spn app id into
the secret's content type text box. And put the spn app key into the secret
value.

A SPN app id looks like this: *XXXX5126-XXXX-XXXX-XXXX-XXXX9b94ac97*; i.e.
a guid.
A SPN app key looks like this:
*7CPXXXXXXXXXXXXV/+XXXXXXXXXXXXXZ+rJGxIeqi1Dc8=* ; i.e. a long string of
gibberish with an '=' at the end.
