### ISSUE TITLE
Azure Monitor Metrics not displaying

### ISSUE THREAD

**Issue by pickledkumkwat** [microsoft/AzureMonitorAddonForSplunk#96]
Hello,

I'm having an issue with the Azure Monitor add-on where the 'Azure Monitor Metrics' input is not displaying. Both the 'Azure Monitor Activity Log' and 'Azure Monitor Diagnostic Logs' inputs show up. All dependencies have been installed.

Any ideas?

**Comment by sebastus** [comment]
If you look in the splunkd.log file, search for azure, then the return code
from attempting to install the metrics data input. What's the return code?

**Comment by pickledkumkwat** [comment]
Unfortunately, I don't see any return codes or errors in the log file.
